import { CustomArticleData } from "./types";

export const ampereToBiot: CustomArticleData = {
  fromUnitId: "ampere",
  toUnitId: "biot",
  seoTitle: "Ampere to Biot Converter (A to Bi) | UnitsConvertors.com",
  metaDescription: "Convert Amperes to Biots (A to Bi) instantly. Master the 0.1 division formula, Biot-Savart law context, worked examples, and cgs-emu unit relationships.",
  canonicalUrl: "https://unitsconvertors.com/ampere-to-biot",
  h1: "Ampere to Biot Converter",
  introduction: [
    "The <strong>Ampere (A)</strong> is the International System of Units (SI) base unit for electric current, whereas the <strong>Biot (Bi)</strong>, historically also termed the <strong>Abampere (abA)</strong>, is the foundational unit of electric current in the centimeter-gram-second electromagnetic unit system (cgs-emu). Named in honor of French physicist and mathematician Jean-Baptiste Biot, the Biot directly reflects magnetic force interactions between current-carrying conductors.",
    "By international scientific definition, one Biot equals exactly 10 amperes (1 Bi = 10 A). Conversely, one ampere is equal to one-tenth of a Biot (0.1 Bi). Converting amperes to Biots is performed by dividing the current in amperes by 10 (or multiplying by 0.1).",
    "This guide presents the complete conversion framework, manual calculation procedures, practical physics examples, conversion tables, electromagnetism history, and technical FAQs."
  ],
  quickAnswer: {
    text: "To convert Amperes to Biots, divide the current in amperes by 10 (or multiply by 0.1). For example, a current of 50 A equals 5 Bi, and 120 A converts to 12 Bi.",
    formulaDisplay: "Bi = A / 10",
    subtext: "1 Ampere = 0.1 Biot (Bi) exactly; 1 Biot = 10 Amperes."
  },
  aboutSourceUnit: {
    title: "What is an Ampere (A)?",
    text: "The <strong>Ampere</strong> (symbol: <strong>A</strong>) is the SI base unit measuring the flow rate of electric charge. Under the 2019 SI redefinition established by the CGPM, the ampere is precisely determined by fixing the elementary charge <em>e</em> at 1.602176634 × 10⁻¹⁹ coulomb. One ampere corresponds to one coulomb of electric charge passing a given point per second (1 C/s)."
  },
  aboutTargetUnit: {
    title: "What is a Biot (Bi)?",
    text: "The <strong>Biot</strong> (symbol: <strong>Bi</strong>), identical to the <strong>abampere</strong> (abA), is the base current unit in the electromagnetic cgs (emu) system. It is defined through Ampère's force law: when two infinitely long, thin parallel conductors spaced 1 centimeter apart in vacuum carry a current of 1 Biot, the magnetic force between them is exactly 2 dynes per centimeter of length."
  },
  relationship: "1 Biot equals exactly 10 Amperes. Therefore, 1 Ampere equals exactly 0.1 (1/10) Biot.",
  relationshipTitle: "Ampere to Biot Metric Scaling",
  relationshipItems: [
    { label: "1 A", value: "0.1 Bi" },
    { label: "5 A", value: "0.5 Bi" },
    { label: "10 A", value: "1.0 Bi" },
    { label: "50 A", value: "5.0 Bi" },
    { label: "100 A", value: "10.0 Bi" },
    { label: "1,000 A (1 kA)", value: "100.0 Bi" }
  ],
  formula: {
    text: "Divide the electric current in amperes by 10 (or multiply by 0.1) to determine the equivalent value in Biots.",
    math: "I_{(Bi)} = \\frac{I_{(A)}}{10} = I_{(A)} × 0.1",
    subtext: "To convert Biots back to amperes, multiply the current value in Biots by 10."
  },
  formulaTitle: "Ampere to Biot Conversion Formula",
  practicalTip: {
    title: "Single Decimal Shift",
    text: "To quickly convert amperes to Biots mentally, simply shift the decimal point one place to the left. For example, 45 A becomes 4.5 Bi."
  },
  expertNote: {
    title: "The Biot-Savart Law Connection",
    text: "Jean-Baptiste Biot and Félix Savart discovered in 1820 that the magnetic field generated by an electric current is inversely proportional to the distance from the wire. The Biot unit was formally adopted by the British Association for the Advancement of Science (BAAS) to simplify electromagnetic force formulas in cgs-emu."
  },
  examples: {
    title: "Manual Calculation Examples",
    items: [
      {
        title: "Example 1: Converting Household Circuit Current",
        subtitle: "A residential kitchen appliance circuit is rated for a continuous load of 15 Amperes. Calculate this current in Biots.",
        steps: [
          "Identify initial current value: I = 15 A.",
          "Apply the conversion formula: I_(Bi) = I_(A) / 10.",
          "Perform division: 15 / 10 = 1.5 Bi.",
          "Result: 15 Amperes equals 1.5 Biots."
        ]
      },
      {
        title: "Example 2: Electric Vehicle Fast Charger Current",
        subtitle: "A DC fast charging station delivers 350 A to an electric vehicle battery pack. Convert this charging current to Biots.",
        steps: [
          "Given parameter: I = 350 A.",
          "Calculation: 350 × 0.1 = 35 Bi.",
          "Conclusion: 350 A corresponds to exactly 35 Biots."
        ]
      },
      {
        title: "Example 3: Industrial Arc Welding Current",
        subtitle: "A heavy-duty submerged arc welder operates at 800 Amperes. Find the current in Biots.",
        steps: [
          "Starting value: I = 800 A.",
          "Apply formula: 800 / 10 = 80 Bi.",
          "Final answer: 800 Amperes equals 80 Biots."
        ]
      }
    ]
  },
  table: {
    title: "Ampere to Biot Conversion Reference Table",
    headers: ["Amperes (A)", "Biots (Bi)", "Abamperes (abA)", "Typical Electrical Context"],
    rows: [
      { fromVal: "1 A", toVal: "0.1 Bi", extra: "0.1 abA", extra2: "Standard 1 A SI base current" },
      { fromVal: "5 A", toVal: "0.5 Bi", extra: "0.5 abA", extra2: "Handheld power tool current" },
      { fromVal: "10 A", toVal: "1 Bi", extra: "1 abA", extra2: "1 Biot benchmark definition" },
      { fromVal: "20 A", toVal: "2 Bi", extra: "2 abA", extra2: "Standard branch circuit breaker" },
      { fromVal: "50 A", toVal: "5 Bi", extra: "5 abA", extra2: "Electric range / oven circuit" },
      { fromVal: "100 A", toVal: "10 Bi", extra: "10 abA", extra2: "Residential service panel main" },
      { fromVal: "200 A", toVal: "20 Bi", extra: "20 abA", extra2: "Modern residential service" },
      { fromVal: "500 A", toVal: "50 Bi", extra: "50 abA", extra2: "Commercial switchgear feeder" },
      { fromVal: "1,000 A (1 kA)", toVal: "100 Bi", extra: "100 abA", extra2: "Distribution substation busway" },
      { fromVal: "10,000 A (10 kA)", toVal: "1,000 Bi", extra: "1,000 abA", extra2: "Industrial arc furnace current" }
    ]
  },
  applications: {
    title: "Scientific and Engineering Applications",
    items: [
      {
        title: "Electromagnetic Physics Research",
        text: "In electromagnetic field theory and magnetostatics, textbooks and research papers examining Biot-Savart relationships often present force formulas in electromagnetic cgs units. Converting experimental currents from amperes to Biots simplifies analytical comparisons."
      },
      {
        title: "High-Field Solenoid and Magnet Design",
        text: "Superconducting magnet windings and particle accelerator beam-steering dipoles handle currents of hundreds to thousands of amperes. When analyzing coil magnetic pressure and Lorentz forces using cgs-emu formulations, currents are expressed in Biots."
      },
      {
        title: "Historical Electrotechnical Literature",
        text: "Technical monographs and laboratory archives from the late 19th and early 20th centuries (including papers by Heaviside, Kelvin, and Rayleigh) utilized Biots and abamperes. Converting these historical figures to amperes allows modern engineers to replicate foundational findings."
      },
      {
        title: "Plasma Physics and Magnetohydrodynamics (MHD)",
        text: "Magnetohydrodynamic simulations of solar flares and fusion reactor z-pinches frequently link fluid pressure (dynes/cm²) with magnetic energy density using cgs-emu units. The Biot provides the natural current scaling in these equations."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes and Misconceptions",
    items: [
      "Multiplying Instead of Dividing: A Biot is 10 times larger than an ampere. Multiplying amperes by 10 instead of dividing produces a value that is 100 times too large.",
      "Confusing the Biot with the Statampere: The Biot belongs to the electromagnetic cgs system (1 Bi = 10 A), whereas the statampere belongs to the electrostatic cgs system (1 statA ≈ 3.3356 × 10⁻¹⁰ A).",
      "Treating Biot and Abampere as Different Units: The Biot and abampere are identical units with identical values (1 Bi = 1 abA = 10 A). Biot is the accepted eponymous name, while abampere is the system prefix name.",
      "Incorrect Symbol Capitalization: The symbol for Biot is 'Bi' (capital B, lowercase i). Avoid confusing it with the chemical element Bismuth (Bi), which shares the same letters."
    ]
  },
  faqs: [
      {
        question: "How many Biots are in one ampere?",
        answer: "There is exactly 0.1 (one-tenth) Biot in one ampere."
      },
      {
        question: "How many amperes are in one Biot?",
        answer: "There are exactly 10 amperes in one Biot (1 Bi = 10 A)."
      },
      {
        question: "What is the difference between a Biot and an abampere?",
        answer: "There is no difference in magnitude. The Biot (Bi) and the abampere (abA) are two names for the exact same cgs-emu unit of electric current (1 Bi = 1 abA = 10 A)."
      },
      {
        question: "Who was the unit Biot named after?",
        answer: "The unit is named after French physicist, astronomer, and mathematician Jean-Baptiste Biot (1774–1862), co-discoverer of the Biot-Savart law of electromagnetism."
      },
      {
        question: "What is the formula to convert amperes to Biots?",
        answer: "The formula is: Current in Bi = Current in A / 10 (or Bi = A × 0.1)."
      },
      {
        question: "How do I convert Biots back to amperes?",
        answer: "Multiply the Biot value by 10. For example, 7 Bi × 10 = 70 A."
      },
      {
        question: "Is the Biot an official SI unit?",
        answer: "No. The Biot is a non-SI unit belonging to the centimeter-gram-second electromagnetic system (cgs-emu). The SI base unit is the ampere."
      },
      {
        question: "How many Biots equal 1 kiloampere?",
        answer: "Because 1 kiloampere equals 1,000 amperes, 1 kA = 1,000 / 10 = 100 Biots."
      },
      {
        question: "How many statamperes are in one Biot?",
        answer: "One Biot equals exactly c statamperes, where c is the speed of light in cm/s. Therefore, 1 Bi = 29,979,245,800 statamperes (approximately 3 × 10¹⁰ statA)."
      },
      {
        question: "How do I convert 25 amperes to Biots?",
        answer: "Divide 25 by 10: 25 / 10 = 2.5 Biots."
      }
    ],
  relatedList: [
    { label: "Ampere to Abampere", from: "ampere", to: "abampere" },
    { label: "Ampere to Statampere", from: "ampere", to: "statampere" },
    { label: "Ampere to Kiloampere", from: "ampere", to: "kiloampere" },
    { label: "Milliampere to Biot", from: "milliampere", to: "biot" },
    { label: "Ampere to Milliampere", from: "ampere", to: "milliampere" }
  ],
  references: [
    "Bureau International des Poids et Mesures (BIPM): The International System of Units (SI Brochure, 9th Edition, 2019).",
    "IEC 60050: International Electrotechnical Vocabulary - Chapter 112: Quantities and Units (cgs-emu units).",
    "NIST Special Publication 811: Guide for the Use of the International System of Units (SI).",
    "Oliver Heaviside: Electromagnetic Theory, Vol. 1, The Electrician Printing and Publishing Co."
  ]
};
