import { CustomArticleData } from "./types";

export const decibelToSoundIntensity: CustomArticleData = {
  fromUnitId: "decibel",
  toUnitId: "sound-intensity",
  seoTitle: "Decibel to Sound Intensity Converter (dB to W/m²) | UnitsConvertors.com",
  metaDescription: "Convert Decibels to Sound Intensity in Watts per square meter (dB to W/m²) with scientific precision. Learn energy flux equations, 10⁻¹² W/m² baseline, formulas, and examples.",
  h1: "Decibel to Sound Intensity Converter",
  introduction: [
    "Sound intensity quantifies the rate of acoustic energy flowing through a unit area perpendicular to the direction of sound wave propagation. While human perception and sound level meters express sound intensity level (SIL) logarithmically in decibels (dB SIL), environmental noise control and acoustic transducer physics measure energy flow in Watts per square meter (W/m²).",
    "Converting sound levels in decibels to sound intensity in W/m² uses the exponential inverse formula based on the standardized human hearing threshold I₀ = 10⁻¹² W/m² (1 picowatt per square meter). On this scale, 0 dB SIL corresponds to 0.000000000001 W/m², whereas a 120 dB sound transmits 1.0 W/m² of acoustic power across each square meter.",
    "This article details the physical principles governing acoustic energy flux, logarithmic-to-linear intensity equations, practical environmental benchmarks, and step-by-step worked calculations."
  ],
  quickAnswer: {
    text: "To convert Decibels to Sound Intensity in Watts per square meter, calculate: I = 10⁻¹² × 10^(dB / 10). For example, 90 dB corresponds to 0.001 W/m² of acoustic intensity.",
    formulaDisplay: "I (W/m²) = 10⁻¹² × 10^(dB / 10)",
    subtext: "Based on international acoustic reference intensity I₀ = 10⁻¹² W/m²."
  },
  aboutSourceUnit: {
    title: "What is a Decibel (dB in Sound Intensity)?",
    text: "The decibel (symbol: dB) is a logarithmic unit expressing sound intensity level relative to 1 picowatt per square meter (10⁻¹² W/m²). Because acoustic power spans over twelve orders of magnitude, decibels condense vast energy ranges into a convenient 0 to 140 dB scale."
  },
  aboutTargetUnit: {
    title: "Understanding Sound Intensity (W/m²)",
    text: "Sound intensity (symbol: I) is a vector quantity defined as the acoustic power per unit area, measured in Watts per square meter (W/m²). It represents the physical sound energy passing through a given surface every second."
  },
  relationship: "Sound intensity level L_I in decibels is defined by L_I = 10 log₁₀(I / I₀), where I₀ = 10⁻¹² W/m². Inverting this logarithmic relationship yields sound intensity: I = 10⁻¹² × 10^(L_I / 10).",
  relationshipTitle: "Decibel to Sound Intensity Scale",
  relationshipItems: [
    { label: "0 dB", value: "10⁻¹² W/m² (0.000000000001 W/m² / hearing threshold)" },
    { label: "30 dB", value: "10⁻⁹ W/m² (0.000000001 W/m² / quiet countryside)" },
    { label: "60 dB", value: "10⁻⁶ W/m² (0.000001 W/m² / normal speech)" },
    { label: "90 dB", value: "10⁻³ W/m² (0.001 W/m² / heavy lawn mower)" },
    { label: "120 dB", value: "1.0 W/m² (Threshold of pain / rock concert front row)" }
  ],
  formula: {
    text: "Multiply the baseline acoustic reference intensity I₀ (10⁻¹² W/m²) by 10 raised to the power of (dB / 10).",
    math: "I = 10⁻¹² × 10^(dB / 10)",
    subtext: "Where I is sound intensity in W/m², and I₀ = 10⁻¹² W/m²."
  },
  formulaTitle: "Decibel to Sound Intensity Conversion Formula",
  practicalTip: {
    title: "The 10 dB Rule for Intensity",
    text: "Because sound intensity is an energy quantity, every 10 dB increase multiplies physical acoustic intensity in W/m² by exactly 10. Every 3 dB increase approximately doubles the acoustic intensity."
  },
  expertNote: {
    title: "ISO 80000-8 Energy Quantity Mechanics",
    text: "Under ISO 80000-8 specifications, sound intensity is an energy flux quantity. Consequently, sound intensity level utilizes the 10 log₁₀(I/I₀) multiplier in contrast to field quantities (such as sound pressure) which use 20 log₁₀(p/p₀)."
  },
  examples: {
    title: "Step-by-Step dB to Sound Intensity Calculations",
    items: [
      {
        title: "Example 1: Converting Spoken Voice (60 dB) to Intensity",
        subtitle: "Calculate sound intensity in W/m² for a 60 dB speech signal.",
        steps: [
          "Identify sound intensity level: 60 dB.",
          "Apply formula: I = 10⁻¹² × 10^(60 / 10).",
          "Simplify exponent: 60 / 10 = 6.",
          "Calculate 10⁶ = 1,000,000.",
          "Multiply: 10⁻¹² × 10⁶ = 10⁻⁶ W/m² = 0.000001 W/m².",
          "Final Result: 60 dB corresponds to 0.000001 W/m² (1 µW/m²)."
        ]
      },
      {
        title: "Example 2: Industrial Compressor Noise (95 dB)",
        subtitle: "Find the acoustic energy flux per square meter generated by a 95 dB compressor.",
        steps: [
          "Identify sound level: 95 dB.",
          "Apply formula: I = 10⁻¹² × 10^(95 / 10) = 10⁻¹² × 10^9.5.",
          "Calculate 10^9.5 ≈ 3,162,277,660.17.",
          "Multiply: 10⁻¹² × 3,162,277,660.17 ≈ 0.003162 W/m².",
          "Final Result: 95 dB yields approximately 0.003162 W/m² (3.162 mW/m²)."
        ]
      },
      {
        title: "Example 3: Rock Concert Audio Rig (110 dB)",
        subtitle: "Determine sound intensity in W/m² for an 110 dB concert speaker array.",
        steps: [
          "Identify sound level: 110 dB.",
          "Apply formula: I = 10⁻¹² × 10^(110 / 10) = 10⁻¹² × 10¹¹.",
          "Calculate exponent: 10⁻¹² × 10¹¹ = 10⁻¹ W/m² = 0.1 W/m².",
          "Final Result: 110 dB equals 0.1 W/m²."
        ]
      }
    ]
  },
  table: {
    title: "Decibel to Sound Intensity Reference Table",
    headers: ["Sound Level (dB)", "Sound Intensity (W/m²)", "Power Ratio (I/I₀)", "Environmental Context"],
    rows: [
      { fromVal: "0 dB", toVal: "0.000000000001 W/m²", extra: "1:1", extra2: "Threshold of human hearing" },
      { fromVal: "20 dB", toVal: "0.0000000001 W/m²", extra: "100:1", extra2: "Rustling leaves in a calm forest" },
      { fromVal: "40 dB", toVal: "0.00000001 W/m²", extra: "10,000:1", extra2: "Quiet residential bedroom" },
      { fromVal: "60 dB", toVal: "0.000001 W/m²", extra: "1,000,000:1", extra2: "Normal spoken conversation" },
      { fromVal: "80 dB", toVal: "0.0001 W/m²", extra: "100,000,000:1", extra2: "Busy city traffic street" },
      { fromVal: "100 dB", toVal: "0.01 W/m²", extra: "10¹⁰:1", extra2: "Pneumatic drill / jackhammer" },
      { fromVal: "120 dB", toVal: "1.0 W/m²", extra: "10¹²:1", extra2: "Threshold of auditory pain" },
      { fromVal: "140 dB", toVal: "100.0 W/m²", extra: "10¹⁴:1", extra2: "Jet engine at 30 meters distance" }
    ]
  },
  applications: {
    title: "Applications of dB to Sound Intensity Conversions",
    items: [
      {
        title: "Acoustic Power Output Measurement",
        text: "Sound intensity probes measure local energy flux around machinery to map noise radiation and determine total sound power levels (L_W)."
      },
      {
        title: "Noise Barrier Efficiency & Building Acoustics",
        text: "Acoustic engineers calculate transmission loss across wall assemblies by comparing sound intensity on both sides of a partition."
      },
      {
        title: "Ultrasonic Medical & Industrial Equipment",
        text: "Medical ultrasound technicians monitor spatial peak intensity in W/m² to ensure diagnostic safety limits."
      }
    ]
  },
  pitfalls: {
    title: "Common Pitfalls to Avoid",
    items: [
      "Dividing dB by 20 instead of 10 when calculating sound intensity exponents (intensity uses 10, pressure uses 20).",
      "Confusing sound intensity in W/m² with total sound power in Watts (power represents total energy emitted per second by a source).",
      "Assuming 0 dB means zero physical energy (0 dB SIL equals 10⁻¹² W/m²)."
    ]
  },
  faqs: [
    {
      question: "How do you convert dB to Sound Intensity in W/m²?",
      answer: "Use the formula I = 10⁻¹² × 10^(dB / 10), where I₀ = 10⁻¹² W/m² is the reference baseline."
    },
    {
      question: "What is 0 dB in W/m²?",
      answer: "0 dB corresponds to 10⁻¹² W/m² (0.000000000001 W/m² or 1 picowatt per square meter)."
    },
    {
      question: "What is 120 dB in W/m²?",
      answer: "120 dB corresponds to exactly 1.0 W/m² of acoustic intensity."
    },
    {
      question: "Why does the sound intensity formula use 10 in the exponent?",
      answer: "Sound intensity is an energy flux quantity. By definition, L_I = 10 log₁₀(I / I₀)."
    },
    {
      question: "What intensity in W/m² corresponds to 90 dB?",
      answer: "90 dB corresponds to 0.001 W/m² (1 milliwatt per square meter)."
    },
    {
      question: "What is the difference between sound intensity and sound pressure?",
      answer: "Sound intensity measures directional energy flow per unit area (W/m²), whereas sound pressure measures local scalar pressure variations (Pa)."
    },
    {
      question: "How much does acoustic intensity increase with a 3 dB rise?",
      answer: "A 3 dB increase approximately doubles the physical acoustic intensity (+10^0.3 ≈ 2×)."
    },
    {
      question: "What is 100 dB in W/m²?",
      answer: "100 dB corresponds to 0.01 W/m²."
    }
  ],
  relatedList: [
    { label: "Decibel to Bel", from: "decibel", to: "bel" },
    { label: "Decibel to Decibel SPL", from: "decibel", to: "decibel-spl" },
    { label: "Decibel to Pascal (Sound)", from: "decibel", to: "pascal-sound" }
  ],
  references: [
    "ISO 80000-8:2020 Quantities and units — Part 8: Acoustics, ISO.",
    "ISO 9614-1:1993 Acoustics — Determination of sound power levels of noise sources using sound intensity.",
    "Fahy, F. J. (1995). Sound Intensity (2nd ed.). E & FN Spon."
  ]
};
