import { CustomArticleData } from "./types";

export const dyneCentimeterToPoundFoot: CustomArticleData = {
  fromUnitId: "dyne-centimeter",
  toUnitId: "pound-foot",
  seoTitle: "Dyne-Centimeter to Pound-Foot Converter (dyn·cm to lb·ft)",
  metaDescription: "Convert dyne-centimeters to pound-feet (dyn·cm to lb·ft) with scientific precision. Exact factor, formula, MEMS to imperial worked examples, charts, and FAQs.",
  canonicalUrl: "https://unitsconvertors.com/torque/dyne-centimeter-to-pound-foot",
  h1: "Dyne-Centimeter to Pound-Foot Converter",
  introduction: [
    "The dyne-centimeter (dyn·cm) and the pound-foot (lb·ft) span opposite ends of the mechanical measurement spectrum. The dyne-centimeter is the fundamental unit of torque in the centimeter-gram-second (CGS) system, standard in micro-electromechanical systems (MEMS), galvanometer movements, quartz crystal balances, and fine horology. The pound-foot (frequently termed the foot-pound in US commercial trade) is the dominant US customary unit for vehicle engine output, structural bolting, and industrial machinery.",
    "Converting from dyne-centimeters to pound-feet requires traversing both a metric-to-imperial unit boundary and a micro-to-macro scale gap of more than seven orders of magnitude. Because one dyne is defined as 10⁻⁵ Newtons and one centimeter is 10⁻² meters, one dyne-centimeter equals exactly 10⁻⁷ Newton-meters. Comparing this with the legal definition of the pound-foot (1 lb·ft = 1.355818 N·m) demonstrates that one pound-foot equals approximately 13,558,179.5 dyne-centimeters. Conversely, one dyne-centimeter is equivalent to approximately 7.37562 × 10⁻⁸ pound-feet.",
    "Specialized test laboratories, aerospace instrumentation developers, and precision transducer manufacturers routinely encounter this conversion when calibrating micro-torque sensors against imperial deadweight calibration standards. This guide covers the physical principles, step-by-step conversion examples, reference tables, calculation guidelines, and authoritative metrology references."
  ],
  quickAnswer: {
    text: "To convert dyne-centimeters to pound-feet, multiply the torque value by 7.37562 × 10⁻⁸ (or divide by 13,558,180). For example, 10,000,000 dyn·cm (1 N·m) equals approximately 0.7376 lb·ft.",
    formulaDisplay: "\\text{lb·ft} = \\text{dyn·cm} \\times 7.37562 \\times 10^{-8} = \\frac{\\text{dyn·cm}}{13{,}558{,}180}",
    subtext: "1 dyne-centimeter equals approximately 7.37562 × 10⁻⁸ pound-feet (1 lb·ft ≈ 13,558,180 dyn·cm)."
  },
  aboutSourceUnit: {
    title: "Understanding the Dyne-Centimeter (dyn·cm)",
    text: "The dyne-centimeter (symbol: dyn·cm) is the CGS unit of torque. It represents the moment generated by one dyne of force acting perpendicularly at a one-centimeter radius (1 dyn·cm = 1 dyn × 1 cm = 10⁻⁷ N·m = 1 erg). It is standard in microscopic physics experiments, torsion balances, sensitive galvanometer coils, and atomic force microscopy cantilevers."
  },
  aboutTargetUnit: {
    title: "Understanding the Pound-Foot (lb·ft)",
    text: "The pound-foot (symbol: lb·ft or lbf·ft) is the US customary and imperial unit of rotational torque. Defined as one avoirdupois pound-force applied perpendicularly at a one-foot moment arm (1 lb·ft = 1 lbf × 1 ft ≈ 1.355818 N·m), it is the primary benchmark for automotive powertrains, industrial drives, and heavy structural bolting."
  },
  relationship: "One pound-force equals 4.4482216152605 Newtons, and one international foot equals 30.48 centimeters. In the CGS system, 1 N = 100,000 dynes. Thus: 1 lb·ft = 4.4482216152605 N × 100,000 dyn/N × 30.48 cm = 13,558,179.483314 dyn·cm. Taking the reciprocal gives 1 dyn·cm ≈ 7.37562149277 × 10⁻⁸ lb·ft.",
  relationshipTitle: "Micro-to-Macro Torque Scale Comparison",
  relationshipItems: [
    { label: "100,000 dyn·cm", value: "0.00738 lb·ft (0.01 N·m — Micro-servo actuator)" },
    { label: "1,000,000 dyn·cm", value: "0.07376 lb·ft (0.1 N·m — Camera gimbal motor)" },
    { label: "10,000,000 dyn·cm", value: "0.73756 lb·ft (1.0 N·m — Coherent SI baseline)" },
    { label: "13,558,180 dyn·cm", value: "1.00000 lb·ft (Exact 1 lb·ft parity threshold)" },
    { label: "50,000,000 dyn·cm", value: "3.68781 lb·ft (5.0 N·m — Collaborative robot joint)" }
  ],
  formula: {
    text: "Multiply the torque in dyne-centimeters by 7.37562 × 10⁻⁸, or divide by 13,558,180, to obtain the equivalent torque in pound-feet.",
    math: "\\tau_{(\\text{lb·ft})} = \\tau_{(\\text{dyn·cm})} \\times 7.3756215 \\times 10^{-8} = \\frac{\\tau_{(\\text{dyn·cm})}}{13{,}558{,}179.5}",
    subtext: "To convert pound-feet back to dyne-centimeters, multiply by 13,558,179.5."
  },
  formulaTitle: "dyn·cm to lb·ft Conversion Formula",
  practicalTip: {
    title: "13.56 Million Shortcut",
    text: "When performing fast estimations, remember that approximately 13.56 million dyn·cm equal 1 lb·ft. Dividing your value in millions of dyn·cm by 13.56 yields an accurate figure within 0.01%."
  },
  expertNote: {
    title: "Precision in Aerospace Calibration",
    text: "Because of the vast difference in magnitude (over 10⁷), always preserve at least six significant figures when converting between dyne-centimeters and pound-feet to prevent rounding truncation during high-precision sensor calibration."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: High-Performance Gimbal Actuator",
        subtitle: "A precision aerospace gyro gimbal stabilizer develops 4,500,000 dyn·cm of peak torque. Convert this value to pound-feet for inclusion in a US flight-qualification report.",
        steps: [
          "State initial torque: 4,500,000 dyn·cm.",
          "Apply conversion factor: lb·ft = 4,500,000 × 7.37562 × 10⁻⁸.",
          "Multiply: 4,500,000 × 0.0000000737562 = 0.331903.",
          "Final Result: 4,500,000 dyn·cm corresponds to approximately 0.332 lb·ft."
        ]
      },
      {
        title: "Example 2: Precision Laboratory Galvanometer",
        subtitle: "A laboratory galvanometer coil exerts 850,000 dyn·cm of full-scale restoring torque. Express this value in pound-feet.",
        steps: [
          "Starting value: 850,000 dyn·cm.",
          "Divide by 13,558,180: 850,000 ÷ 13,558,180 ≈ 0.06269.",
          "Final Result: 850,000 dyn·cm equals approximately 0.0627 lb·ft."
        ]
      },
      {
        title: "Example 3: Miniature Rotary Torsion Spring",
        subtitle: "A precision metrology spring is preloaded to 12,000,000 dyn·cm. Find its torque in pound-feet.",
        steps: [
          "Starting value: 12,000,000 dyn·cm.",
          "Multiply by 7.37562 × 10⁻⁸: 12,000,000 × 7.37562 × 10⁻⁸ = 0.88507.",
          "Final Result: 12,000,000 dyn·cm equals approximately 0.885 lb·ft."
        ]
      }
    ]
  },
  table: {
    title: "Dyne-Centimeter to Pound-Foot Reference Table",
    headers: ["Dyne-Centimeters (dyn·cm)", "Pound-Feet (lb·ft)", "Pound-Inches (lb·in)", "Engineering Context"],
    rows: [
      { fromVal: "100,000 dyn·cm", toVal: "0.007376 lb·ft", extra: "0.0885 lb·in", extra2: "Micro-servo actuator (1 N·cm)" },
      { fromVal: "500,000 dyn·cm", toVal: "0.036878 lb·ft", extra: "0.4425 lb·in", extra2: "Precision camera iris motor" },
      { fromVal: "1,000,000 dyn·cm", toVal: "0.073756 lb·ft", extra: "0.8851 lb·in", extra2: "Drone pan-tilt camera gimbal" },
      { fromVal: "2,500,000 dyn·cm", toVal: "0.184391 lb·ft", extra: "2.2127 lb·in", extra2: "NEMA 14 stepper motor" },
      { fromVal: "5,000,000 dyn·cm", toVal: "0.368781 lb·ft", extra: "4.4254 lb·in", extra2: "Standard NEMA 17 3D printer motor" },
      { fromVal: "10,000,000 dyn·cm", toVal: "0.737562 lb·ft", extra: "8.8507 lb·in", extra2: "1.0 N·m SI metric baseline" },
      { fromVal: "13,558,180 dyn·cm", toVal: "1.000000 lb·ft", extra: "12.000 lb·in", extra2: "Exact 1.0 lb·ft parity point" },
      { fromVal: "20,000,000 dyn·cm", toVal: "1.475124 lb·ft", extra: "17.701 lb·in", extra2: "NEMA 23 CNC leadscrew motor" },
      { fromVal: "30,000,000 dyn·cm", toVal: "2.212686 lb·ft", extra: "26.552 lb·in", extra2: "High-power NEMA 23 stepper motor" },
      { fromVal: "50,000,000 dyn·cm", toVal: "3.687811 lb·ft", extra: "44.254 lb·in", extra2: "Collaborative robotic arm joint" },
      { fromVal: "100,000,000 dyn·cm", toVal: "7.375621 lb·ft", extra: "88.507 lb·in", extra2: "10 N·m industrial rotary table" },
      { fromVal: "200,000,000 dyn·cm", toVal: "14.75124 lb·ft", extra: "177.01 lb·in", extra2: "Heavy packaging machine spindle" }
    ]
  },
  applications: {
    title: "Key Industry & Metrology Applications",
    items: [
      {
        title: "Aerospace Gyroscopic Sensor Verification",
        text: "Inertial navigation sensors and satellite reaction wheels quote micro-disturbance torques in dyn·cm that must be converted to lb·ft to evaluate reaction forces against spacecraft structural mounting frames."
      },
      {
        title: "Calibration Laboratory Cross-Standards Testing",
        text: "National calibration metrologists cross-certify CGS torsion balances against US customary deadweight torque calibration rigs rated in pound-feet."
      },
      {
        title: "High-Precision Rotary Stage Interfacing",
        text: "Scientific research institutions matching foreign micro-stepper motors with US-built optical benches translate between dyn·cm and lb·ft to verify mechanical stiffness criteria."
      },
      {
        title: "Micro-Turbine & Wind Tunnel Model Testing",
        text: "Miniature wind tunnel aerodynamic models measure rotor and control surface hinge moments in dyn·cm, which aerodynamicists convert to lb·ft to align with US aircraft design tables."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes When Converting dyn·cm to lb·ft",
    items: [
      "Confusing Pound-Feet with Pound-Inches: 1 lb·ft equals 12 lb·in. Because both involve small decimal multipliers, confusing the two causes a massive 12x error.",
      "Misplacing Scientific Exponents: The multiplier is approximately 7.38 × 10⁻⁸. Using 10⁻⁷ or 10⁻⁹ changes the torque value by a factor of 10 in either direction.",
      "Conflating Energy (Ergs) with Torque: While 1 dyn·cm equals 1 erg mathematically, energy is a scalar quantity, whereas torque is a rotational vector. Do not report torque as foot-pounds of energy.",
      "Rounding Too Early: Due to the seven orders of magnitude span, rounding intermediate values prematurely introduces significant cumulative errors in flight-control calculations."
    ]
  },
  faqs: [
    {
      question: "How do I convert dyne-centimeters to pound-feet?",
      answer: "Multiply the torque in dyne-centimeters by 7.37562 × 10⁻⁸, or divide it by 13,558,180. For example, 13,558,180 dyn·cm divided by 13,558,180 equals exactly 1.0 lb·ft."
    },
    {
      question: "How many dyne-centimeters are in one pound-foot?",
      answer: "There are approximately 13,558,179.5 (roughly 13.56 million) dyne-centimeters in one pound-foot."
    },
    {
      question: "What is 1 dyn·cm in pound-feet?",
      answer: "One dyne-centimeter equals approximately 7.37562 × 10⁻⁸ pound-feet (0.0000000737562 lb·ft)."
    },
    {
      question: "Why is the conversion factor so small?",
      answer: "The dyne is a microscopic CGS force unit (1/100,000 of a Newton), and the centimeter is 1/30.48 of a foot. In contrast, one pound-force is 4.45 Newtons acting over an entire foot. It requires over 13.5 million dyn·cm to equal a single lb·ft."
    },
    {
      question: "How do I convert dyn·cm to pound-inches (lb·in) instead?",
      answer: "Multiply the dyn·cm value by 8.85075 × 10⁻⁷ (or divide by 1,129,848). Because there are 12 inches in a foot, the torque in lb·in is 12 times larger than in lb·ft."
    },
    {
      question: "What is 10,000,000 dyn·cm in pound-feet?",
      answer: "10,000,000 dyn·cm (which equals 1 Newton-meter) converts to approximately 0.73756 lb·ft."
    },
    {
      question: "Is it correct to call this foot-pounds?",
      answer: "Colloquially in North America, 'foot-pound' is common. However, engineering organizations (ASME, SAE, NIST) strictly recommend 'pound-foot' for torque to prevent confusion with the foot-pound of mechanical work."
    },
    {
      question: "What is 1,000,000 dyn·cm in lb·ft?",
      answer: "1,000,000 dyn·cm equals approximately 0.07376 lb·ft (or 0.8851 lb·in)."
    },
    {
      question: "Can I use this conversion for torque wrenches?",
      answer: "Standard mechanical torque wrenches operate in lb·ft, but their minimum scale is usually around 5 to 10 lb·ft (roughly 68 to 135 million dyn·cm). Micro-torque measurements in dyn·cm are tested on specialized digital calibration benches rather than mechanical click wrenches."
    },
    {
      question: "What is the exact mathematical conversion ratio?",
      answer: "Using international definitions: lb·ft = dyn·cm × 10⁻⁷ ÷ 1.3558179483314004. This yields the exact multiplier of approximately 7.37562149277 × 10⁻⁸."
    }
  ],
  relatedList: [
    { label: "Dyne-Centimeter to Newton-Meter", from: "dyne-centimeter", to: "newton-meter" },
    { label: "Dyne-Centimeter to Pound-Inch", from: "dyne-centimeter", to: "pound-inch" },
    { label: "Pound-Foot to Dyne-Centimeter", from: "pound-foot", to: "dyne-centimeter" },
    { label: "Dyne-Centimeter to Newton-Centimeter", from: "dyne-centimeter", to: "newton-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Pound-Foot to Dyne-Centimeter Conversion Guide",
      description: "Convert macroscopic imperial torque into micro-scale CGS units for precision instrumentation.",
      from: "pound-foot",
      to: "dyne-centimeter"
    },
    {
      title: "Dyne-Centimeter to Pound-Inch Conversion Guide",
      description: "Convert CGS torque into imperial inch-pounds for precision electronics fasteners.",
      from: "dyne-centimeter",
      to: "pound-inch"
    }
  ],
  references: [
    "ASME B107.300: Manual Torque Tools — Precision and Calibration",
    "ISO 80000-4: Quantities and Units — Mechanics",
    "NIST Special Publication 811: Guide for the Use of the International System of Units",
    "IEEE Standard 268: Metric Practice"
  ]
};
