import { CustomArticleData } from "./types";

export const dyneCentimeterToKilogramForceMeter: CustomArticleData = {
  fromUnitId: "dyne-centimeter",
  toUnitId: "kilogram-force-meter",
  seoTitle: "Dyne-Centimeter to Kilogram-Force Meter Converter (dyn·cm to kgf·m)",
  metaDescription: "Convert dyne-centimeters to kilogram-force meters (dyn·cm to kgf·m) accurately. Standard gravity factor, formula, industrial and laboratory examples, tables, and FAQs.",
  canonicalUrl: "https://unitsconvertors.com/torque/dyne-centimeter-to-kilogram-force-meter",
  h1: "Dyne-Centimeter to Kilogram-Force Meter Converter",
  introduction: [
    "The dyne-centimeter (dyn·cm) and the kilogram-force meter (kgf·m, also known as the kilopond-meter, kp·m) represent opposite extremes of metric mechanical engineering. The dyne-centimeter is the coherent unit of torque and rotational work in the centimeter-gram-second (CGS) system, standard in micro-electromechanical systems (MEMS), galvanometer movements, quartz crystal balances, and fine horology. The kilogram-force meter is a classic gravitational metric unit historically utilized across European, Japanese, and Russian heavy engineering, automotive dynos, lifting hoists, and marine propulsion.",
    "Converting from dyne-centimeters to kilogram-force meters bridges the gap between micro-scale laboratory physics and heavy industrial plant machinery, spanning nearly eight orders of physical magnitude. Because one kilogram-force is defined through standard Earth gravitational acceleration (g₀ = 9.80665 m/s²), one kilogram-force meter equals exactly 9.80665 Newton-meters, which equates to exactly 98,066,500 dyne-centimeters (9.80665 × 10⁷ dyn·cm). Conversely, one dyne-centimeter corresponds to approximately 1.01972 × 10⁻⁸ kilogram-force meters.",
    "Metrology engineers, test bench technicians, and industrial automation retrofitter teams encounter this conversion when correlating micro-friction sensor data with industrial hoist specifications or translating historical Japanese Industrial Standard (JIS) machinery ledgers into modern scientific research databases. This guide covers the complete physical derivation, worked micro-to-macro examples, a reference conversion table, calculation pitfalls, and authoritative standards citations."
  ],
  quickAnswer: {
    text: "To convert dyne-centimeters to kilogram-force meters, multiply the torque value by 1.01972 × 10⁻⁸ (or divide by 98,066,500). For example, 100,000,000 dyn·cm (10 N·m) equals approximately 1.0197 kgf·m.",
    formulaDisplay: "\\text{kgf·m} = \\text{dyn·cm} \\times 1.01972 \\times 10^{-8} = \\frac{\\text{dyn·cm}}{98{,}066{,}500}",
    subtext: "1 dyne-centimeter equals approximately 1.01972 × 10⁻⁸ kilogram-force meters (1 kgf·m = 98,066,500 dyn·cm)."
  },
  aboutSourceUnit: {
    title: "Understanding the Dyne-Centimeter (dyn·cm)",
    text: "The dyne-centimeter (symbol: dyn·cm) is the CGS unit of torque. It quantifies the moment generated by one dyne of force acting perpendicularly at a one-centimeter radius (1 dyn·cm = 1 dyn × 1 cm = 10⁻⁷ N·m = 1 erg). It is standard in microfluidics, precision galvanometer movements, torsion wire balances, and atomic force microscopy."
  },
  aboutTargetUnit: {
    title: "Understanding the Kilogram-Force Meter (kgf·m)",
    text: "The kilogram-force meter (symbol: kgf·m or kp·m) is a gravitational metric unit of torque. Defined as the turning moment exerted by one kilogram of mass under standard gravitational acceleration (9.80665 m/s²) acting on a one-meter moment arm (1 kgf·m = 1 kgf × 1 m = 9.80665 N·m), it is common in Japanese Industrial Standards (JIS) and legacy European machinery documentation."
  },
  relationship: "Standard gravitational acceleration is internationally defined as g₀ = 9.80665 m/s². One kilogram-force equals exactly 9.80665 Newtons. Since 1 N = 100,000 dynes and 1 m = 100 cm, 1 kgf·m = 9.80665 N × 100,000 dyn/N × 100 cm = 98,066,500 dyn·cm. Taking the reciprocal gives 1 dyn·cm = 1 / 98,066,500 kgf·m ≈ 1.019716212978 × 10⁻⁸ kgf·m.",
  relationshipTitle: "Micro-to-Macro Torque Scale Points",
  relationshipItems: [
    { label: "1,000,000 dyn·cm", value: "0.01020 kgf·m (Camera gimbal stabilizer motor)" },
    { label: "10,000,000 dyn·cm", value: "0.10197 kgf·m (1.0 N·m SI metric baseline)" },
    { label: "49,033,250 dyn·cm", value: "0.50000 kgf·m (Mid-size industrial leadscrew drive)" },
    { label: "98,066,500 dyn·cm", value: "1.00000 kgf·m (Exact 1.0 kgf·m parity threshold)" },
    { label: "500,000,000 dyn·cm", value: "5.09858 kgf·m (Heavy packaging machinery spindle)" }
  ],
  formula: {
    text: "Multiply the torque in dyne-centimeters by 1.01972 × 10⁻⁸, or divide by 98,066,500, to obtain the equivalent torque in kilogram-force meters.",
    math: "\\tau_{(\\text{kgf·m})} = \\tau_{(\\text{dyn·cm})} \\times 1.0197162 \\times 10^{-8} = \\frac{\\tau_{(\\text{dyn·cm})}}{98{,}066{,}500}",
    subtext: "To convert kilogram-force meters back to dyne-centimeters, multiply by 98,066,500."
  },
  formulaTitle: "dyn·cm to kgf·m Exact Conversion Formula",
  practicalTip: {
    title: "100 Million Field Rule",
    text: "Because 98,066,500 is within 2% of 100 million (10⁸), you can quickly approximate kgf·m on the fly by dividing dyn·cm by 100,000,000. For instance, 50,000,000 dyn·cm is approximately 0.5 kgf·m (actual: 0.510 kgf·m)."
  },
  expertNote: {
    title: "Beware of kg·cm vs kgf·m",
    text: "Do not confuse kilogram-force meters (kgf·m) with kilogram-force centimeters (kg·cm). One kgf·m equals exactly 100 kgf·cm. While hobby RC servos quote holding torque in kg·cm (where 1 kg·cm ≈ 980,665 dyn·cm), industrial machinery uses kgf·m (where 1 kgf·m = 98,066,500 dyn·cm)."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: High-Power Actuator Benchmark",
        subtitle: "An industrial micro-motion drive develops 150,000,000 dyn·cm of peak torque. Convert this value to kilogram-force meters for a Japanese factory maintenance report.",
        steps: [
          "State initial torque: 150,000,000 dyn·cm.",
          "Apply conversion factor: kgf·m = 150,000,000 × 1.01972 × 10⁻⁸.",
          "Compute: 150,000,000 ÷ 98,066,500 = 1.52957.",
          "Final Result: 150,000,000 dyn·cm equals approximately 1.53 kgf·m."
        ]
      },
      {
        title: "Example 2: Precision Laboratory Dynamometer",
        subtitle: "A micro-turbomachine dynamometer measures 25,000,000 dyn·cm of brake torque. Express this torque in kilogram-force meters.",
        steps: [
          "Starting value: 25,000,000 dyn·cm.",
          "Divide by 98,066,500: 25,000,000 ÷ 98,066,500 ≈ 0.25493.",
          "Final Result: 25,000,000 dyn·cm corresponds to approximately 0.255 kgf·m."
        ]
      },
      {
        title: "Example 3: Stepper Motor Torque Verification",
        subtitle: "A NEMA 23 stepper motor produces 20,000,000 dyn·cm (2 N·m) of holding torque. Convert this to kilogram-force meters.",
        steps: [
          "Starting value: 20,000,000 dyn·cm.",
          "Multiply by 1.01972 × 10⁻⁸: 20,000,000 × 1.01972 × 10⁻⁸ = 0.20394.",
          "Final Result: 20,000,000 dyn·cm equals approximately 0.204 kgf·m."
        ]
      }
    ]
  },
  table: {
    title: "Dyne-Centimeter to Kilogram-Force Meter Reference Table",
    headers: ["Dyne-Centimeters (dyn·cm)", "Kilogram-Force Meters (kgf·m)", "Newton-Meters (N·m) Equiv.", "Industrial Application Context"],
    rows: [
      { fromVal: "1,000,000 dyn·cm", toVal: "0.01020 kgf·m", extra: "0.10 N·m", extra2: "Camera gimbal stabilizer motor" },
      { fromVal: "5,000,000 dyn·cm", toVal: "0.05099 kgf·m", extra: "0.50 N·m", extra2: "Standard NEMA 17 3D printer motor" },
      { fromVal: "10,000,000 dyn·cm", toVal: "0.10197 kgf·m", extra: "1.00 N·m", extra2: "1.0 N·m metric milestone" },
      { fromVal: "20,000,000 dyn·cm", toVal: "0.20394 kgf·m", extra: "2.00 N·m", extra2: "Compact NEMA 23 leadscrew motor" },
      { fromVal: "50,000,000 dyn·cm", toVal: "0.50986 kgf·m", extra: "5.00 N·m", extra2: "Heavy NEMA 23 CNC milling drive" },
      { fromVal: "98,066,500 dyn·cm", toVal: "1.00000 kgf·m", extra: "9.81 N·m", extra2: "Exact 1.0 kgf·m parity threshold" },
      { fromVal: "150,000,000 dyn·cm", toVal: "1.52957 kgf·m", extra: "15.0 N·m", extra2: "Small industrial robot wrist joint" },
      { fromVal: "200,000,000 dyn·cm", toVal: "2.03943 kgf·m", extra: "20.0 N·m", extra2: "Automated warehouse AGV steering motor" },
      { fromVal: "300,000,000 dyn·cm", toVal: "3.05915 kgf·m", extra: "30.0 N·m", extra2: "Heavy-duty positioning rotary table" },
      { fromVal: "500,000,000 dyn·cm", toVal: "5.09858 kgf·m", extra: "50.0 N·m", extra2: "Industrial planetary gearbox output" },
      { fromVal: "750,000,000 dyn·cm", toVal: "7.64787 kgf·m", extra: "75.0 N·m", extra2: "Crane cable drum positioning brake" },
      { fromVal: "1,000,000,000 dyn·cm", toVal: "10.1972 kgf·m", extra: "100 N·m", extra2: "Heavy industrial assembly spindle" }
    ]
  },
  applications: {
    title: "Engineering & Machinery Applications",
    items: [
      {
        title: "Japanese Industrial Standard (JIS) Machine Overhauls",
        text: "Maintenance technicians upgrading older Japanese CNC lathes and automated machining centers translate older JIS catalog specs in kgf·m into CGS and metric micro-torque sensor readings."
      },
      {
        title: "Laboratory Dynamometer to Industrial Output Matching",
        text: "Research dynamometers recording high-speed micro-turbines in dyn·cm must be matched against heavy industrial gear reducer ratings quoted in kgf·m."
      },
      {
        title: "Cable Winch & Hoisting Mechanism Evaluation",
        text: "Industrial lifting winches and crane drums quote capacity in kgf·m. High-precision electric drives evaluated in CGS research must be converted to confirm safe overhead hoisting limits."
      },
      {
        title: "Marine Propulsion & Rudder Steering Mechanisms",
        text: "Naval steering telemetry and rudder angle feedback sensors often translate micro-deflection moments into heavy kilogram-force meter mechanical limits."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes When Converting dyn·cm to kgf·m",
    items: [
      "Confusing kgf·m with kgf·cm: 1 kgf·m equals exactly 100 kgf·cm. Confusing the meter arm with the centimeter arm will cause an error of two orders of magnitude (100x).",
      "Misplacing the Decimal Point: The conversion factor is approximately 1.02 × 10⁻⁸ (eight decimal places). A dropped zero produces a 10x or 100x magnitude error.",
      "Assuming Local Gravity Changes the Conversion: The kilogram-force is legally defined with standard gravity fixed at exactly 9.80665 m/s² worldwide, regardless of local elevation.",
      "Multiplying Instead of Dividing: Because 1 kgf·m is nearly 100 million times larger than 1 dyn·cm, the numerical value in kgf·m must be vastly smaller."
    ]
  },
  faqs: [
    {
      question: "How do I convert dyne-centimeters to kilogram-force meters?",
      answer: "Multiply the torque value in dyne-centimeters by 1.01972 × 10⁻⁸, or divide it by 98,066,500. For example, 98,066,500 dyn·cm divided by 98,066,500 yields exactly 1.0 kgf·m."
    },
    {
      question: "How many dyne-centimeters are in one kilogram-force meter?",
      answer: "There are exactly 98,066,500 dyne-centimeters in one kilogram-force meter (1 kgf·m = 98,066,500 dyn·cm)."
    },
    {
      question: "What is 1 dyn·cm in kilogram-force meters?",
      answer: "One dyne-centimeter equals approximately 1.01972 × 10⁻⁸ kilogram-force meters (0.0000000101972 kgf·m)."
    },
    {
      question: "Where did the factor 98,066,500 come from?",
      answer: "Standard Earth gravity is 9.80665 m/s², so 1 kgf = 9.80665 N. Since 1 N = 100,000 dynes and 1 m = 100 cm, 1 kgf·m = 9.80665 × 100,000 × 100 = 98,066,500 dyn·cm."
    },
    {
      question: "What is the difference between kgf·m and kg·cm?",
      answer: "One kilogram-force meter (kgf·m) uses a 1-meter moment arm, while one kilogram-force centimeter (kg·cm) uses a 1-centimeter arm. Therefore, 1 kgf·m equals exactly 100 kg·cm (and 1 kg·cm = 980,665 dyn·cm)."
    },
    {
      question: "What is 10,000,000 dyn·cm in kilogram-force meters?",
      answer: "10,000,000 dyn·cm (which equals 1 Newton-meter) converts to approximately 0.10197 kgf·m."
    },
    {
      question: "Is kilogram-force meter an official SI unit?",
      answer: "No. The kilogram-force meter is a non-SI gravitational metric unit. The official SI derived unit of torque is the Newton-meter (N·m)."
    },
    {
      question: "Is kgf·m the same as kp·m?",
      answer: "Yes. The kilopond-meter (kp·m) is an alternative name used in Germany and parts of Europe for the kilogram-force meter (1 kp·m = 1 kgf·m = 9.80665 N·m)."
    },
    {
      question: "How do I convert dyn·cm to kg·cm instead of kgf·m?",
      answer: "Multiply the dyn·cm value by 1.01972 × 10⁻⁶ (or divide by 980,665). For example, 9,806,650 dyn·cm equals approximately 10 kg·cm."
    },
    {
      question: "What is 50,000,000 dyn·cm in kilogram-force meters?",
      answer: "50,000,000 dyn·cm converts to approximately 0.5099 kgf·m (50,000,000 ÷ 98,066,500 ≈ 0.50986 kgf·m)."
    }
  ],
  relatedList: [
    { label: "Kilogram-Force Meter to Dyne-Centimeter", from: "kilogram-force-meter", to: "dyne-centimeter" },
    { label: "Dyne-Centimeter to Newton-Meter", from: "dyne-centimeter", to: "newton-meter" },
    { label: "Newton-Centimeter to Kilogram-Force Meter", from: "newton-centimeter", to: "kilogram-force-meter" },
    { label: "Dyne-Centimeter to Newton-Centimeter", from: "dyne-centimeter", to: "newton-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Kilogram-Force Meter to Dyne-Centimeter Conversion Guide",
      description: "Convert legacy gravitational torque specifications into microscopic CGS units.",
      from: "kilogram-force-meter",
      to: "dyne-centimeter"
    },
    {
      title: "Dyne-Centimeter to Newton-Meter Conversion Guide",
      description: "Convert CGS torque into coherent SI base units for modern engineering models.",
      from: "dyne-centimeter",
      to: "newton-meter"
    }
  ],
  references: [
    "BIPM: The International System of Units (SI Brochure, 9th Edition)",
    "ISO 80000-4: Quantities and Units — Mechanics",
    "JIS Z 8202: Quantities and Units — Mechanics (Japanese Industrial Standards)",
    "NIST Special Publication 811: Guide for the Use of the International System of Units"
  ]
};
