import { CustomArticleData } from "./types";

export const kilogramForceMeterToNewtonCentimeter: CustomArticleData = {
  fromUnitId: "kilogram-force-meter",
  toUnitId: "newton-centimeter",
  seoTitle: "Kilogram-Force Meter to Newton-Centimeter Converter (kgf·m to N·cm)",
  metaDescription: "Convert kilogram-force meters to Newton-centimeters (kgf·m to N·cm) accurately. Exact 980.665 factor, micro-fastener calculations, tables, and FAQs.",
  canonicalUrl: "https://unitsconvertors.com/kilogram-force-meter-to-newton-centimeter",
  h1: "Kilogram-Force Meter to Newton-Centimeter Converter",
  introduction: [
    "The kilogram-force meter (symbol: kgf·m or m·kg) and the Newton-centimeter (symbol: N·cm) connect traditional gravitational metric engineering with modern sub-multiple SI precision assembly. While the kilogram-force meter is a legacy standard commonly found across Japanese (JIS) and European industrial equipment documentation, the Newton-centimeter is the prevailing international metric unit for micro-motors, electronic assemblies, medical robotics, and optical instruments.",
    "Converting kilogram-force meters to Newton-centimeters allows engineers and technicians to translate legacy torque specifications into the graduated ranges of modern electronic torque screwdrivers and micro-actuators. Because one Newton-meter contains exactly 100 Newton-centimeters and one kilogram-force meter equals exactly 9.80665 Newton-meters, multiplying by 100 reveals that 1 kilogram-force meter equals exactly 980.665 Newton-centimeters. Conversely, 1 N·cm equals approximately 0.00101972 kgf·m.",
    "This technical guide explains the exact physical derivation, provides clear step-by-step conversion calculations, supplies a reference conversion table for precision components, and highlights practical assembly guidelines."
  ],
  quickAnswer: {
    text: "To convert kilogram-force meters to Newton-centimeters, multiply the torque value by exactly 980.665. For example, a delicate machine spindle torque of 0.05 kgf·m converts to approximately 49.03 N·cm.",
    formulaDisplay: "\\text{N·cm} = \\text{kgf·m} \\times 980.665",
    subtext: "1 kilogram-force meter equals exactly 980.665 Newton-centimeters. 1 N·cm equals approximately 0.00101972 kgf·m."
  },
  aboutSourceUnit: {
    title: "Understanding the Kilogram-Force Meter (kgf·m)",
    text: "The kilogram-force meter (symbol: kgf·m, m·kg, or kp·m) is a gravitational metric unit of torque representing the turning moment generated by one kilogram-force acting at a perpendicular radius of one meter (1 kgf·m = 9.80665 N·m). It is prevalent in legacy Japanese machine blueprints, older automotive manuals, and maritime machinery records."
  },
  aboutTargetUnit: {
    title: "Understanding the Newton-Centimeter (N·cm)",
    text: "The Newton-centimeter (symbol: N·cm) is an SI sub-multiple unit of torque defined as one Newton of force applied at a perpendicular distance of one centimeter (1 N·cm = 0.01 N·m). It is the standard rating unit for micro-stepper motors, drone gimbals, surgical devices, and precision micro-screws (M1.6 to M4)."
  },
  relationship: "The mathematical relationship between kilogram-force meters and Newton-centimeters follows directly from the definition of standard gravity: 1 kgf = 9.80665 N, and 1 meter = 100 centimeters. Therefore: 1 kgf·m = 9.80665 N × 100 cm = 980.665 N·cm (exact). The reciprocal factor is 1 / 980.665 = 0.001019716213 kgf·m.",
  relationshipTitle: "Torque Scale Hierarchy (kgf·m vs N·cm)",
  relationshipItems: [
    { label: "0.01 kgf·m", value: "9.81 N·cm (Micro-fasteners in mobile devices & optics)" },
    { label: "0.05 kgf·m", value: "49.03 N·cm (Miniature drone motors & PCB standoffs)" },
    { label: "0.10 kgf·m", value: "98.07 N·cm (Small instrument dial knobs & M3 screws)" },
    { label: "0.50 kgf·m", value: "490.33 N·cm (Bicycle stem faceplate bolts)" },
    { label: "1.00 kgf·m", value: "980.67 N·cm (Automotive valve cover flange bolts)" },
    { label: "2.00 kgf·m", value: "1,961.33 N·cm (Engine thermostat housing bolts)" }
  ],
  formula: {
    text: "Multiply the torque value in kilogram-force meters by 980.665 to obtain the torque in Newton-centimeters.",
    math: "\\tau_{(\\text{N·cm})} = \\tau_{(\\text{kgf·m})} \\times 980.665",
    subtext: "Alternatively: Divide the kilogram-force meter value by 0.00101972."
  },
  formulaTitle: "Kilogram-Force Meter to Newton-Centimeter Conversion Formula",
  practicalTip: {
    title: "Quick 1000x Mental Approximation",
    text: "To estimate N·cm rapidly without a calculator, multiply the kgf·m value by 1000 and subtract 2% (e.g., 0.1 kgf·m × 1000 = 100; minus 2% = 98 N·cm; exact is 98.07 N·cm)."
  },
  expertNote: {
    title: "Prefix Distinctions: N·cm vs cN·m vs mN·m",
    text: "1 N·cm equals exactly 1 cN·m (centiNewton-meter). However, 1 N·cm equals 10 mN·m (milliNewton-meters). Always double-check torque driver display indicators to verify whether you are reading centi- or milli-Newtons."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Precision Stepper Motor Coupling",
        subtitle: "A legacy Japanese automated assembly drawing specifies 0.08 kgf·m for an encoder shaft coupling. Convert to Newton-centimeters for a digital torque driver.",
        steps: [
          "State the initial torque: 0.08 kgf·m.",
          "Apply the exact factor: N·cm = 0.08 × 980.665.",
          "Calculate: 0.08 × 980.665 = 78.4532 N·cm.",
          "Final Result: 0.08 kgf·m equals approximately 78.45 N·cm (set driver to 78.5 N·cm)."
        ]
      },
      {
        title: "Example 2: Optical Sensor Adjustment Retainer",
        subtitle: "Convert a tightening torque of 0.025 kgf·m into Newton-centimeters.",
        steps: [
          "Starting value: 0.025 kgf·m.",
          "Multiply by 980.665: 0.025 × 980.665 = 24.5166 N·cm.",
          "Final Result: 0.025 kgf·m corresponds to 24.52 N·cm."
        ]
      },
      {
        title: "Example 3: Small Water Pump Impeller Nut",
        subtitle: "Convert a torque rating of 0.35 kgf·m into Newton-centimeters.",
        steps: [
          "Starting value: 0.35 kgf·m.",
          "Multiply by 980.665: 0.35 × 980.665 = 343.23275 N·cm.",
          "Final Result: 0.35 kgf·m equals approximately 343.23 N·cm."
        ]
      }
    ]
  },
  table: {
    title: "Kilogram-Force Meter to Newton-Centimeter Reference Table",
    headers: ["Kilogram-Force Meters (kgf·m)", "Newton-Centimeters (N·cm)", "Newton-Meters (N·m)", "Pound-Inches (lb·in)", "Assembly Application"],
    rows: [
      { fromVal: "0.01 kgf·m", toVal: "9.81 N·cm", extra: "0.098 N·m", extra2: "0.87 lb·in", extra3: "Miniature sensor casing screws" },
      { fromVal: "0.02 kgf·m", toVal: "19.61 N·cm", extra: "0.196 N·m", extra2: "1.74 lb·in", extra3: "Printed circuit board M2 standoffs" },
      { fromVal: "0.05 kgf·m", toVal: "49.03 N·cm", extra: "0.490 N·m", extra2: "4.34 lb·in", extra3: "Drone brushless motor stator mount" },
      { fromVal: "0.10 kgf·m", toVal: "98.07 N·cm", extra: "0.981 N·m", extra2: "8.68 lb·in", extra3: "Terminal strip M3 electrical screws" },
      { fromVal: "0.20 kgf·m", toVal: "196.13 N·cm", extra: "1.961 N·m", extra2: "17.36 lb·in", extra3: "Carburetor float bowl fasteners" },
      { fromVal: "0.30 kgf·m", toVal: "294.20 N·cm", extra: "2.942 N·m", extra2: "26.04 lb·in", extra3: "Bicycle disc rotor M5 bolts" },
      { fromVal: "0.40 kgf·m", toVal: "392.27 N·cm", extra: "3.923 N·m", extra2: "34.72 lb·in", extra3: "Throttle body TPS sensor screws" },
      { fromVal: "0.50 kgf·m", toVal: "490.33 N·cm", extra: "4.903 N·m", extra2: "43.40 lb·in", extra3: "Handlebar stem faceplate hardware" },
      { fromVal: "0.75 kgf·m", toVal: "735.50 N·cm", extra: "7.355 N·m", extra2: "65.10 lb·in", extra3: "Motorcycle clutch spring bolts" },
      { fromVal: "1.00 kgf·m", toVal: "980.67 N·cm", extra: "9.807 N·m", extra2: "86.80 lb·in", extra3: "Valve cover flange bolts" },
      { fromVal: "1.50 kgf·m", toVal: "1,471.00 N·cm", extra: "14.71 N·m", extra2: "130.19 lb·in", extra3: "Thermostat housing bolts" },
      { fromVal: "2.00 kgf·m", toVal: "1,961.33 N·cm", extra: "19.61 N·m", extra2: "173.59 lb·in", extra3: "Spark plugs in aluminum heads" }
    ]
  },
  applications: {
    title: "Precision Engineering Applications",
    items: [
      {
        title: "Automated Electronics & Robotics Assembly",
        text: "Production lines assembling robotic arms, pick-and-place grippers, and PCB enclosures rely on smart electric torque drivers calibrated in N·cm. Converting legacy Japanese engineering notes to N·cm allows accurate driver profile programming."
      },
      {
        title: "Medical Diagnostic Equipment & Implants",
        text: "CT scanner gantry slip rings, surgical robotic arms, and diagnostic imaging equipment built under international standards specify tightening parameters in N·cm."
      },
      {
        title: "Drone & RC Actuator Mechanisms",
        text: "High-performance brushless drone motors, gimbal stabilizer pivots, and servo linkages mandate torque limits expressed in Newton-centimeters to prevent thread strip-out."
      },
      {
        title: "Optical & Metrology Instrumentation",
        text: "Precision laser alignment stages and spectrometer optical benches use torque drivers in N·cm to maintain micro-radian mechanical positioning."
      }
    ]
  },
  pitfalls: {
    title: "Common Pitfalls in Micro-Torque Conversion",
    items: [
      "Confusing N·cm with N·m: 1 kgf·m is 9.81 N·m, but 980.67 N·cm. A factor of 100 difference exists between the two; setting a tool to 980 N·m will destroy the equipment.",
      "Mistaking kgf·m for kgf·cm: 1 kgf·m = 100 kgf·cm. 1 kgf·cm equals only 9.80665 N·cm. Failing to check the distance prefix will produce a 100-fold over-torque.",
      "Driver clutch inertia at high RPM: Electric torque screwdrivers can overdrive micro-fasteners due to motor inertia if driven at excessive rotation speeds.",
      "Using worn driver bits: In micro-screws (M1 to M3), bit wear causes cam-out and head stripping before reaching target N·cm torque."
    ]
  },
  faqs: [
    {
      question: "How do I convert kilogram-force meters to Newton-centimeters?",
      answer: "Multiply the kilogram-force meter (kgf·m) value by 980.665. For example, 0.1 kgf·m × 980.665 = 98.07 N·cm."
    },
    {
      question: "How many Newton-centimeters are in 1 kilogram-force meter?",
      answer: "There are exactly 980.665 Newton-centimeters in one kilogram-force meter."
    },
    {
      question: "What is the difference between N·cm and N·m?",
      answer: "1 Newton-meter (N·m) equals 100 Newton-centimeters (N·cm). 1 N·cm equals 0.01 N·m."
    },
    {
      question: "What is 0.5 kgf·m in N·cm?",
      answer: "0.5 kgf·m equals approximately 490.33 N·cm (0.5 × 980.665 = 490.3325 N·cm)."
    },
    {
      question: "How do I convert N·cm back to kgf·m?",
      answer: "Divide the Newton-centimeter value by 980.665 (or multiply by 0.00101972). For example, 500 N·cm / 980.665 = 0.5099 kgf·m."
    },
    {
      question: "Is kgf·cm the same as N·cm?",
      answer: "No. 1 kilogram-force centimeter (kgf·cm) equals approximately 9.80665 N·cm. 1 kgf·m equals 100 kgf·cm (980.665 N·cm)."
    },
    {
      question: "What is 1 kgf·m in N·cm?",
      answer: "1 kgf·m equals exactly 980.665 N·cm."
    },
    {
      question: "What tool is used to measure torque in Newton-centimeters?",
      answer: "Electronic torque screwdrivers, dial-indicating torque screwdrivers, and micro-torque analyzers."
    }
  ],
  relatedList: [
    { label: "Kilogram-Force Meter to Newton-Meter", from: "kilogram-force-meter", to: "newton-meter" },
    { label: "Kilogram-Force Meter to Dyne-Centimeter", from: "kilogram-force-meter", to: "dyne-centimeter" },
    { label: "Pound-Inch to Newton-Centimeter", from: "pound-inch", to: "newton-centimeter" },
    { label: "Newton-Meter to Newton-Centimeter", from: "newton-meter", to: "newton-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Kilogram-Force Meter to Newton-Meter Conversion Guide",
      description: "Convert legacy gravitational metric torque ratings to standard international SI Newton-meters.",
      from: "kilogram-force-meter",
      to: "newton-meter"
    },
    {
      title: "Pound-Inch to Newton-Centimeter Conversion Guide",
      description: "Step-by-step conversion factors between imperial inch-pounds and precision metric micro-fastener values.",
      from: "pound-inch",
      to: "newton-centimeter"
    }
  ],
  references: [
    "ISO 80000-4: Quantities and units — Part 4: Mechanics",
    "JIS B 0101: Japanese Industrial Standard for Screw Threads and Fasteners",
    "ISO 6789-1: Hand torque tools — Requirements and test methods",
    "NIST Guide for the Use of the International System of Units (SI)"
  ]
};
