import { CustomArticleData } from "./types";

export const kilopascalToMmhg: CustomArticleData = {
  fromUnitId: "kilopascal",
  toUnitId: "mmhg",
  seoTitle: "Kilopascal to Millimeter of Mercury Converter (kPa to mmHg)",
  metaDescription: "Convert kilopascals to millimeters of mercury (kPa to mmHg) with medical precision. Formulas, blood pressure charts (120/80 mmHg), worked examples, and FAQs.",
  h1: "Kilopascal to Millimeter of Mercury Converter",
  introduction: [
    "Converting kilopascals (kPa) to millimeters of mercury (mmHg) is a fundamental calculation in clinical medicine, cardiology, pulmonology, biomedical engineering, and barometric instrumentation. While international SI guidelines, medical device regulatory standards, and European hospital monitors often record physiological pressures in kilopascals, clinical practitioners worldwide universally diagnose and monitor blood pressure, intracranial pressure, and respiratory parameters in millimeters of mercury.",
    "By conventional physical definition, one millimeter of mercury (mmHg) is the hydrostatic pressure exerted by a 1-millimeter column of mercury at 0 °C under standard gravity ($g = 9.80665\\text{ m/s}^2$), equal to approximately 133.322 Pascals (0.1333224 kPa). Consequently, one kilopascal equals approximately 7.50062 mmHg. To convert kilopascals into millimeters of mercury, multiply the pressure value in kilopascals by 7.500616 (or divide by 0.1333224).",
    "This comprehensive guide details the mathematical derivation, clinical blood pressure benchmarks (such as converting 16.0 kPa to 120 mmHg systolic), step-by-step conversion examples, medical lookup tables, and answers to frequently asked clinical and engineering questions."
  ],
  quickAnswer: {
    text: "To convert kilopascals to millimeters of mercury, multiply the pressure in kilopascals by 7.500616 (or divide by 0.1333224). For example, a normal arterial systolic pressure of 16.0 kPa equals approximately 120.0 mmHg, and 10.7 kPa equals 80.3 mmHg.",
    formulaDisplay: "mmHg = kPa × 7.500616 ≈ \\frac{kPa}{0.1333224}",
    subtext: "1 kPa ≈ 7.5006158 mmHg.\n1 mmHg = 0.133322387 kPa (133.322 Pa)."
  },
  aboutSourceUnit: {
    title: "Understanding the Kilopascal (kPa)",
    text: "The kilopascal (symbol: kPa) is an official SI decimal multiple equal to 1,000 Pascals (1,000 N/m²). Widely used in hospital ventilators, cardiovascular monitoring equipment across Europe and Asia, and clinical research literature, it represents standard metric pressure."
  },
  aboutTargetUnit: {
    title: "Understanding the Millimeter of Mercury (mmHg)",
    text: "The millimeter of mercury (symbol: mmHg) is a manometric unit of pressure defined as the pressure generated by a 1 mm column of mercury at 0 °C (133.322 Pa). It remains the global gold standard for human blood pressure (sphygmomanometers), intraocular pressure (tonometry), and central venous pressure."
  },
  relationship: "One kilopascal equals approximately 7.50062 mmHg, and one millimeter of mercury equals approximately 0.1333224 kPa. Multiplying any kilopascal reading by 7.50062 yields its direct equivalent in millimeters of mercury.",
  relationshipTitle: "Kilopascal to mmHg Clinical & Barometric Scale",
  relationshipItems: [
    { label: "1.333 kPa", value: "10.0 mmHg (Normal intraocular / CSF pressure)" },
    { label: "2.666 kPa", value: "20.0 mmHg (Venous hypertension threshold)" },
    { label: "10.67 kPa", value: "80.0 mmHg (Normal diastolic blood pressure)" },
    { label: "16.00 kPa", value: "120.0 mmHg (Normal systolic blood pressure)" },
    { label: "18.67 kPa", value: "140.0 mmHg (Stage 1 hypertension systolic)" },
    { label: "101.325 kPa", value: "760.00 mmHg (Standard sea-level atmosphere)" }
  ],
  formula: {
    text: "Multiply the pressure in kilopascals by 7.500616 (or divide by 0.1333224) to obtain millimeters of mercury.",
    math: "\\text{mmHg} = \\text{kPa} \\times 7.500616 \\approx \\frac{\\text{kPa}}{0.1333224}",
    subtext: "To convert millimeters of mercury back to kilopascals, multiply the mmHg value by 0.1333224."
  },
  formulaTitle: "Kilopascal to Millimeter of Mercury Formula",
  practicalTip: {
    title: "Clinical Mental Math: × 7.5 Shortcut",
    text: "To convert kPa to mmHg rapidly in clinical settings: multiply by 7.5 (e.g., 16 kPa × 7.5 = 120 mmHg, and 12 kPa × 7.5 = 90 mmHg). To reverse (mmHg to kPa), multiply by 4 and divide by 30 (e.g., 120 × 4 = 480 ÷ 30 = 16 kPa)."
  },
  expertNote: {
    title: "Medical Ventilator and Blood Gas Notation",
    text: "In arterial blood gas (ABG) analyses, partial pressures of oxygen ($PaO_2$) and carbon dioxide ($PaCO_2$) are reported in kPa in the UK, Canada, and parts of Europe, but in mmHg in the US. A normal $PaO_2$ of 10–13 kPa equals 75–100 mmHg."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Patient Arterial Blood Pressure (16.0 kPa)",
        subtitle: "A digital patient monitor in a European hospital reads a systolic blood pressure of 16.0 kPa. Convert this value to mmHg.",
        steps: [
          "State starting systolic pressure: 16.0 kPa.",
          "Apply conversion multiplier: mmHg = 16.0 × 7.500616.",
          "Calculate: 16.0 × 7.500616 = 120.0098.",
          "Result: 16.0 kPa equals exactly 120.0 mmHg (standard optimal systolic blood pressure)."
        ]
      },
      {
        title: "Example 2: Diastolic Blood Pressure (10.7 kPa)",
        subtitle: "Convert a diastolic pressure measurement of 10.7 kPa into mmHg for clinical documentation.",
        steps: [
          "Identify diastolic pressure: 10.7 kPa.",
          "Apply formula: mmHg = 10.7 × 7.500616.",
          "Calculate: 10.7 × 7.500616 = 80.2566.",
          "Result: 10.7 kPa corresponds to approximately 80.3 mmHg (standard optimal diastolic pressure)."
        ]
      },
      {
        title: "Example 3: Intraocular Pressure (IOP) Screening (2.4 kPa)",
        subtitle: "An ophthalmology tonometer measures intraocular pressure at 2.4 kPa. Convert to mmHg to check for glaucoma risk.",
        steps: [
          "State intraocular pressure: 2.4 kPa.",
          "Apply conversion: mmHg = 2.4 × 7.500616.",
          "Calculate: 2.4 × 7.500616 = 18.0015.",
          "Result: 2.4 kPa equals approximately 18.0 mmHg (within normal 10–21 mmHg reference range)."
        ]
      }
    ]
  },
  table: {
    title: "Kilopascal to Millimeter of Mercury Reference Table",
    headers: ["Kilopascals (kPa)", "Millimeters of Mercury (mmHg)", "Torr Equivalent", "Medical / Physiological Context"],
    rows: [
      { fromVal: "1.0 kPa", toVal: "7.5006 mmHg", extra: "7.501 Torr", extra2: "Low venous pressure / Capillary hydrostatic level" },
      { fromVal: "2.0 kPa", toVal: "15.001 mmHg", extra: "15.001 Torr", extra2: "Normal intraocular pressure (10–21 mmHg)" },
      { fromVal: "2.67 kPa", toVal: "20.027 mmHg", extra: "20.027 Torr", extra2: "Upper limit of normal intracranial pressure (ICP)" },
      { fromVal: "5.33 kPa", toVal: "39.978 mmHg", extra: "39.978 Torr", extra2: "Normal arterial PaCO2 (35–45 mmHg)" },
      { fromVal: "10.0 kPa", toVal: "75.006 mmHg", extra: "75.006 Torr", extra2: "Lower bound normal arterial PaO2" },
      { fromVal: "10.67 kPa", toVal: "80.032 mmHg", extra: "80.032 Torr", extra2: "Normal adult diastolic blood pressure" },
      { fromVal: "12.0 kPa", toVal: "90.007 mmHg", extra: "90.007 Torr", extra2: "Mean arterial pressure (MAP) reference" },
      { fromVal: "16.0 kPa", toVal: "120.010 mmHg", extra: "120.010 Torr", extra2: "Normal adult systolic blood pressure" },
      { fromVal: "18.67 kPa", toVal: "140.037 mmHg", extra: "140.037 Torr", extra2: "Stage 1 hypertension systolic threshold" },
      { fromVal: "101.325 kPa", toVal: "760.000 mmHg", extra: "760.000 Torr", extra2: "Standard sea-level atmospheric pressure" }
    ]
  },
  applications: {
    title: "Primary Medical & Physiological Applications",
    items: [
      {
        title: "Clinical Blood Pressure Monitoring",
        text: "Healthcare providers convert electronic non-invasive blood pressure (NIBP) monitor data between kPa and mmHg to ensure international compatibility across medical charts."
      },
      {
        title: "Arterial Blood Gas (ABG) Diagnostics",
        text: "Pulmonologists and critical care nurses convert blood oxygen ($PaO_2$) and carbon dioxide ($PaCO_2$) values from European kPa lab printouts to standard North American mmHg scales."
      },
      {
        title: "Intracranial & Intraocular Pressure Management",
        text: "Neurosurgeons and ophthalmologists monitor brain parenchyma (ICP) and eye globe pressures (IOP), translating sensor values from kPa to clinical mmHg thresholds."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes to Avoid",
    items: [
      "Dividing by 7.5 instead of multiplying: Converting from kPa to mmHg increases the numerical value by roughly 7.5 times.",
      "Rounding 7.5006 to 7.0: A rough multiplier of 7 results in an unacceptable 7% medical calculation error.",
      "Confusing mmHg with cmH2O: $1\\text{ mmHg} \\approx 1.3595\\text{ cmH}_2\\text{O}$ (ventilator peak inspiratory pressure is often in cmH2O)."
    ]
  },
  faqs: [
    {
      question: "How do you convert kilopascals to mmHg?",
      answer: "Multiply the pressure value in kilopascals by 7.500616 (or divide by 0.1333224)."
    },
    {
      question: "What is 16 kPa in blood pressure mmHg?",
      answer: "16 kPa equals exactly 120.0 mmHg (standard optimal systolic blood pressure: 16 × 7.500616 ≈ 120 mmHg)."
    },
    {
      question: "What is 10.7 kPa in blood pressure mmHg?",
      answer: "10.7 kPa equals approximately 80.3 mmHg (standard optimal diastolic blood pressure: 10.7 × 7.500616 ≈ 80.3 mmHg)."
    },
    {
      question: "How many mmHg are in 1 kPa?",
      answer: "There are approximately 7.50062 mmHg in 1 kilopascal."
    },
    {
      question: "How do you convert mmHg back to kPa?",
      answer: "Multiply the mmHg value by 0.1333224 (or divide by 7.500616). For example, 120 mmHg × 0.1333224 ≈ 16.0 kPa."
    },
    {
      question: "Why do some medical monitors show kPa instead of mmHg?",
      answer: "Countries following strict SI metric regulations (such as parts of Europe, Canada, and China) utilize the official SI kilopascal on patient monitors, whereas others retain historical mmHg."
    },
    {
      question: "What is 101.325 kPa in mmHg?",
      answer: "101.325 kPa equals exactly 760.0 mmHg (standard atmospheric pressure at sea level)."
    },
    {
      question: "What is normal blood pressure in kPa?",
      answer: "A standard blood pressure reading of 120/80 mmHg corresponds to approximately 16.0 / 10.7 kPa."
    }
  ],
  relatedList: [
    { label: "Millimeter of Mercury to Kilopascal", from: "mmhg", to: "kilopascal" },
    { label: "Pascal to Millimeter of Mercury", from: "pascal", to: "mmhg" },
    { label: "Kilopascal to Torr", from: "kilopascal", to: "torr" },
    { label: "Kilopascal to PSI", from: "kilopascal", to: "psi" },
    { label: "Kilopascal to Bar", from: "kilopascal", to: "bar" }
  ],
  references: [
    "American Heart Association (AHA): Understanding Blood Pressure Readings.",
    "ISO 81060-1:2007 Non-invasive sphygmomanometers — Part 1: Requirements and test methods.",
    "NIST Special Publication 330: The International System of Units (SI)."
  ]
};
