import { CustomArticleData } from "./types";

export const newtonMeterToPoundFoot: CustomArticleData = {
  fromUnitId: "newton-meter",
  toUnitId: "pound-foot",
  seoTitle: "Newton-Meter to Pound-Foot Converter (N·m to lb·ft)",
  metaDescription: "Convert Newton-meters to pound-feet (N·m to lb·ft) with exact conversion factors, calculation formulas, worked automotive examples, reference tables, and FAQs.",
  h1: "Newton-Meter to Pound-Foot Converter",
  introduction: [
    "The Newton-meter (N·m) and the pound-foot (lb·ft, often called foot-pound) represent the two most widely referenced units of rotational force and torque in modern engineering. The Newton-meter serves as the official coherent derived unit in the International System of Units (SI), while the pound-foot remains the standard across United States automotive, aerospace, and heavy machinery industries.",
    "Converting Newton-meters to pound-feet is routine when interpreting vehicle engine output dyno charts, configuring calibrated digital torque wrenches, or verifying fastener tensioning specifications across international service manuals. Because one pound-force equals exactly 4.4482216152605 Newtons and one foot equals exactly 0.3048 meters, one pound-foot equates to 1.3558179483314004 Newton-meters. Consequently, converting from N·m to lb·ft requires multiplying by approximately 0.73756215 (or dividing by 1.35581795).",
    "This technical guide explains the underlying physical mechanics of rotational moments, provides exact step-by-step conversion equations, details real-world automotive and industrial assembly examples, and answers common fastener calibration questions."
  ],
  quickAnswer: {
    text: "To convert Newton-meters to pound-feet, multiply the torque value by 0.737562 (or divide by 1.355818). For example, a modern electric vehicle producing 400 N·m of motor torque generates approximately 295.02 lb·ft of rotational torque.",
    formulaDisplay: "\\text{lb·ft} = \\text{N·m} \\times 0.737562",
    subtext: "1 Newton-meter equals exactly 0.7375621493 pound-feet."
  },
  aboutSourceUnit: {
    title: "Understanding the Newton-Meter (N·m)",
    text: "The Newton-meter (symbol: N·m) is the SI derived unit of torque (also known as moment of force). Dimensionally defined as one Newton of perpendicular force applied at a radial leverage distance of one meter from the pivot axis (1 N·m = 1 N × 1 m = 1 kg·m²/s²), it characterizes the rotational effort generated by electric motors, combustion engines, turbine shafts, and threaded bolts across global manufacturing standards."
  },
  aboutTargetUnit: {
    title: "Understanding the Pound-Foot (lb·ft)",
    text: "The pound-foot (symbol: lb·ft or lbf·ft) is the imperial and US customary unit of torque. It represents the rotational moment produced by one pound-force exerted perpendicularly at the end of a one-foot lever arm (1 lb·ft = 1 lbf × 1 ft). Widely referenced throughout North American automotive specifications, structural bolting standards (AISC/RCSC), and industrial power equipment, it prevents confusing torque with scalar energy (foot-pounds)."
  },
  relationship: "The mathematical relationship between Newton-meters and pound-feet derives from the exact definitions of the standard pound-force (4.4482216152605 N) and international foot (0.3048 m): 1 lb·ft = 4.4482216152605 N × 0.3048 m = 1.3558179483314 N·m. Conversely, 1 N·m = 1 / 1.3558179483314 ≈ 0.7375621493 lb·ft.",
  relationshipTitle: "Torque Scale Equivalence (SI vs Imperial)",
  relationshipItems: [
    { label: "1 N·m", value: "0.73756 lb·ft (Precision electronics & small appliance fasteners)" },
    { label: "20 N·m", value: "14.751 lb·ft (Bicycle crank bolts & engine spark plugs)" },
    { label: "100 N·m", value: "73.756 lb·ft (Automotive aluminum alloy wheel lug nuts)" },
    { label: "250 N·m", value: "184.391 lb·ft (Commercial chassis suspension mounting bolts)" },
    { label: "500 N·m", value: "368.781 lb·ft (Turbocharged performance engine peak output)" }
  ],
  formula: {
    text: "Multiply the torque in Newton-meters by the conversion coefficient 0.73756215 to find the equivalent torque in pound-feet.",
    math: "\\tau_{(\\text{lb·ft})} = \\tau_{(\\text{N·m})} \\times 0.73756215",
    subtext: "Alternatively: Divide the Newton-meter figure by 1.35581795."
  },
  formulaTitle: "N·m to lb·ft Mathematical Formula",
  practicalTip: {
    title: "Fast Workshop Rule of Thumb",
    text: "For quick shop-floor estimation without a calculator, subtract one-quarter (25%) from the Newton-meter value and add 1% back (e.g., 100 N·m → 100 - 25 = 75; 75 - 1.25 ≈ 73.8 lb·ft, within 0.1% of the exact 73.76 lb·ft)."
  },
  expertNote: {
    title: "Torque (lb·ft) vs Work Energy (ft·lb)",
    text: "While dimensional analysis shows both units consist of force multiplied by length, metrology standards (NIST SP 811 and ISO 80000-4) advise using 'pound-foot' (lb·ft) exclusively for vector torque to avoid confusion with 'foot-pound' (ft·lb), which denotes scalar mechanical energy or work."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Automotive Wheel Lug Nut Torque",
        subtitle: "Convert a European vehicle manufacturer lug nut specification of 140 N·m into pound-feet.",
        steps: [
          "Record the starting torque in Newton-meters: 140 N·m.",
          "Apply the conversion factor: lb·ft = 140 × 0.73756215.",
          "Perform the multiplication: 140 × 0.73756215 = 103.2587.",
          "Final Result: 140 N·m equals approximately 103.26 lb·ft."
        ]
      },
      {
        title: "Example 2: Electric Vehicle Motor Output",
        subtitle: "Convert an electric drive motor rated at 310 N·m of continuous torque to imperial pound-feet.",
        steps: [
          "Identify the target torque value: 310 N·m.",
          "Divide by the imperial unit base constant: 310 ÷ 1.35581795.",
          "Calculate: 310 ÷ 1.35581795 = 228.6443.",
          "Final Result: 310 N·m equals 228.64 lb·ft of shaft torque."
        ]
      },
      {
        title: "Example 3: Spark Plug Installation Torque",
        subtitle: "A service manual specifies 25 N·m for aluminum cylinder head spark plugs. Find the setting in lb·ft.",
        steps: [
          "Identify initial metric value: 25 N·m.",
          "Multiply by 0.73756215: 25 × 0.73756215 = 18.43905.",
          "Final Result: 25 N·m corresponds to 18.44 lb·ft (or ~221 lb·in)."
        ]
      }
    ]
  },
  table: {
    title: "Newton-Meter to Pound-Foot Reference Chart",
    headers: ["Newton-Meters (N·m)", "Pound-Feet (lb·ft)", "Common Mechanical & Automotive Context"],
    rows: [
      { fromVal: "5 N·m", toVal: "3.69 lb·ft", extra: "Bicycle stem clamp and disc rotor M5 bolts" },
      { fromVal: "10 N·m", toVal: "7.38 lb·ft", extra: "Engine valve cover & plastic intake manifold bolts" },
      { fromVal: "20 N·m", toVal: "14.75 lb·ft", extra: "Oil drain plug on aluminum oil pans" },
      { fromVal: "35 N·m", toVal: "25.81 lb·ft", extra: "Brake caliper guide pin & bracket bolts" },
      { fromVal: "50 N·m", toVal: "36.88 lb·ft", extra: "Small displacement motorcycle engine cylinder bolts" },
      { fromVal: "75 N·m", toVal: "55.32 lb·ft", extra: "Suspension sway bar end-link hardware" },
      { fromVal: "100 N·m", toVal: "73.76 lb·ft", extra: "Compact car wheel lug nuts" },
      { fromVal: "120 N·m", toVal: "88.51 lb·ft", extra: "Midsize sedan wheel lug nuts (M12 stud standard)" },
      { fromVal: "150 N·m", toVal: "110.63 lb·ft", extra: "Full-size SUV / Light truck wheel lugs (M14 stud)" },
      { fromVal: "200 N·m", toVal: "147.51 lb·ft", extra: "Crankshaft harmonic balancer pulley bolt" },
      { fromVal: "300 N·m", toVal: "221.27 lb·ft", extra: "Axle spindle nut / front drive axle hub assembly" },
      { fromVal: "500 N·m", toVal: "368.78 lb·ft", extra: "V8 performance crate engine maximum torque" },
      { fromVal: "1,000 N·m", toVal: "737.56 lb·ft", extra: "Heavy-duty commercial diesel truck axle fasteners" }
    ]
  },
  applications: {
    title: "Key Engineering & Industrial Applications",
    items: [
      {
        title: "Automotive Repair & Assembly",
        text: "Automotive technicians regularly convert manufacturer fastener specifications between metric N·m (European/Asian platforms) and US customary lb·ft torque wrenches when replacing cylinder heads, suspension arms, and wheels."
      },
      {
        title: "Electric Vehicle & Powertrain Testing",
        text: "Dynamometer facilities measure instantaneous electric motor shaft torque in Newton-meters and convert figures to pound-feet for North American consumer window stickers and powertrain comparison sheets."
      },
      {
        title: "Aerospace Structural Bolting",
        text: "Aircraft maintenance engineering requires rigorous compliance with FAA structural joint guidelines, converting metric airframe assembly specifications into calibrated imperial torque tooling limits."
      },
      {
        title: "Robotics & Actuator Sizing",
        text: "Automation engineers convert harmonic drive gearhead output torque ratings between N·m and lb·ft when calculating payload carrying capabilities and servo motor holding currents."
      }
    ]
  },
  pitfalls: {
    title: "Critical Torque Calculation Errors to Avoid",
    items: [
      "Confusing Pound-Feet (lb·ft) with Pound-Inches (lb·in): 1 lb·ft equals 12 lb·in. Setting a torque wrench in lb·ft when lb·in was intended will over-torque the bolt by 1,200%, instantly snapping threads.",
      "Ignoring Fastener Lubrication State: Conversion gives the exact theoretical torque, but applying wet lubricant (anti-seize, oil, or threadlocker) lowers the required tightening torque by 15% to 30% compared to dry fastener specs.",
      "Using Scalar Energy Conversion Factors: While 1 J = 1 N·m, torque must always be treated as a moment vector. Ensure tools and documentation use lb·ft rather than scalar energy equivalents.",
      "Inverting the Ratio: Dividing by 0.73756 instead of multiplying will inflate the torque value by 35%, risking stripped threads and warped cylinder heads."
    ]
  },
  faqs: [
    {
      question: "How do I convert Newton-meters to pound-feet quickly?",
      answer: "Multiply the Newton-meter value by 0.737562. For instance, 120 N·m × 0.737562 = 88.51 lb·ft. Alternatively, divide the N·m figure by 1.355818."
    },
    {
      question: "What is the exact difference between lb·ft and ft·lb?",
      answer: "Technically, 'lb·ft' (pound-foot) denotes rotational torque (a vector cross-product of force and distance), while 'ft·lb' (foot-pound) denotes mechanical energy or work (a scalar dot product). In automotive trade speak they are often used interchangeably, but engineering standards recommend lb·ft for torque."
    },
    {
      question: "What is 100 N·m in lb·ft?",
      answer: "100 N·m equals approximately 73.76 lb·ft (100 × 0.737562 = 73.7562 lb·ft). This is a standard tightening torque for automotive alloy wheel lug nuts."
    },
    {
      question: "Why do European cars use N·m while American cars use lb·ft?",
      answer: "European manufacturers operate on the International System of Units (SI metric), where the Newton is the standard unit of force and meter is length. North American manufacturers adhere to US Customary units where pound-force and feet are the historical standard."
    },
    {
      question: "How many Newton-meters are in 1 pound-foot?",
      answer: "1 pound-foot equals exactly 1.3558179483314 Newton-meters (commonly rounded to 1.3558 N·m)."
    },
    {
      question: "Can I use a foot-pound torque wrench for N·m specifications?",
      answer: "Yes, provided you convert the metric specification to pound-feet before setting your wrench (multiply N·m by 0.737562). Many modern dual-scale torque wrenches display both markings on the barrel."
    },
    {
      question: "What is 50 N·m in lb·ft?",
      answer: "50 N·m equals approximately 36.88 lb·ft (50 × 0.737562 = 36.8781 lb·ft)."
    },
    {
      question: "How does torque relate to engine horsepower?",
      answer: "Horsepower is calculated from torque and engine speed: Horsepower = (Torque in lb·ft × RPM) / 5252. If torque is measured in N·m, Power in kW = (Torque in N·m × RPM) / 9549."
    }
  ],
  relatedList: [
    { label: "Pound-Foot to Newton-Meter", from: "pound-foot", to: "newton-meter" },
    { label: "Newton-Meter to Pound-Inch", from: "newton-meter", to: "pound-inch" },
    { label: "Newton-Meter to Kilogram-Force Meter", from: "newton-meter", to: "kilogram-force-meter" },
    { label: "Newton-Meter to Newton-Centimeter", from: "newton-meter", to: "newton-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Pound-Foot to Newton-Meter Conversion Guide",
      description: "Reverse conversion equations, torque wrench setup instructions, and fastener tightening reference charts.",
      from: "pound-foot",
      to: "newton-meter"
    },
    {
      title: "Newton-Meter to Pound-Inch Conversion Guide",
      description: "Convert precision torque ratings for electronics, carbon fiber bicycle components, and small mechanical fasteners.",
      from: "newton-meter",
      to: "pound-inch"
    }
  ],
  references: [
    "NIST Special Publication 811: Guide for the Use of the International System of Units (SI)",
    "ISO 80000-4: Quantities and Units — Part 4: Mechanics",
    "ASME B107.300: Manual Torque Tools — Precision & Calibration Standards",
    "SAE J1701: Torque-Tension Relationship for Threaded Fasteners"
  ]
};
