import { CustomArticleData } from "./types";

export const newtonMeterToKilogramForceMeter: CustomArticleData = {
  fromUnitId: "newton-meter",
  toUnitId: "kilogram-force-meter",
  seoTitle: "Newton-Meter to Kilogram-Force Meter Converter (N·m to kgf·m)",
  metaDescription: "Convert Newton-meters to kilogram-force meters (N·m to kgf·m) accurately. Formula, 9.80665 standard gravity factor, heavy equipment examples, tables, and FAQs.",
  h1: "Newton-Meter to Kilogram-Force Meter Converter",
  introduction: [
    "The Newton-meter (N·m) and the kilogram-force meter (kgf·m, also written as m·kg or meter-kilogram) are two metric units of torque and rotational moment. The Newton-meter is the standard coherent unit in the International System of Units (SI), whereas the kilogram-force meter belongs to the traditional Gravitational Metric System (MKS gravitational), which historically defined force through the weight of one kilogram under standard Earth gravity.",
    "Converting Newton-meters to kilogram-force meters is frequently required when working with classic European and Asian automotive service documentation (notably Japanese Domestic Market / JDM technical sheets), crane lifting torque specifications, industrial winch load calculations, and legacy civil engineering blueprints. By international metrological agreement, standard gravity ($g_0$) is fixed at exactly 9.80665 m/s². Therefore, one kilogram-force meter equals exactly 9.80665 Newton-meters. Converting from N·m to kgf·m requires dividing by 9.80665 (or multiplying by approximately 0.10197162).",
    "This technical guide explains gravitational metric mechanics, provides step-by-step conversion equations, details heavy vehicle and industrial machinery examples, and includes an extensive engineering reference chart."
  ],
  quickAnswer: {
    text: "To convert Newton-meters to kilogram-force meters, divide the torque value by 9.80665 (or multiply by 0.101972). For example, a heavy diesel truck producing 980.665 N·m of crankshaft torque develops exactly 100 kgf·m of torque.",
    formulaDisplay: "\\text{kgf·m} = \\text{N·m} \\div 9.80665",
    subtext: "1 Newton-meter equals approximately 0.1019716 kilogram-force meters."
  },
  aboutSourceUnit: {
    title: "Understanding the Newton-Meter (N·m)",
    text: "The Newton-meter (symbol: N·m) is the SI base derived unit of rotational torque and mechanical moment. Defined as the turning effort generated by a force of one Newton acting perpendicular to a lever arm of one meter (1 N·m = 1 N × 1 m), it is independent of local gravitational variation and forms the global engineering baseline for all powertrain and fastener specifications."
  },
  aboutTargetUnit: {
    title: "Understanding the Kilogram-Force Meter (kgf·m)",
    text: "The kilogram-force meter (symbol: kgf·m or m·kgf) is a gravitational metric unit of torque. It represents the moment produced by the gravitational force exerted on a mass of one kilogram (1 kgf = 9.80665 N) applied at a perpendicular distance of one meter (1 kgf·m = 1 kgf × 1 m = 9.80665 N·m). Widely used in vintage Japanese automotive manuals, hydraulic press ratings, and heavy crane load charts."
  },
  relationship: "The exact conversion factor is governed strictly by the standard acceleration due to Earth gravity ($g_n = 9.80665\\text{ m/s}^2$): 1 kgf·m = 9.80665 N·m. Conversely, 1 N·m = 1 / 9.80665 ≈ 0.1019716213 kgf·m.",
  relationshipTitle: "Torque Comparison Benchmark (SI vs Gravitational Metric)",
  relationshipItems: [
    { label: "9.80665 N·m", value: "1.000 kgf·m (Base gravitational torque unit)" },
    { label: "50 N·m", value: "5.099 kgf·m (Motorcycle cylinder head studs)" },
    { label: "100 N·m", value: "10.197 kgf·m (Automotive wheel hub bolts)" },
    { label: "400 N·m", value: "40.789 kgf·m (Commercial diesel van engine torque)" },
    { label: "1,000 N·m", value: "101.972 kgf·m (Heavy construction excavator slewing torque)" }
  ],
  formula: {
    text: "Divide the torque value in Newton-meters by the standard gravitational constant 9.80665 to calculate the equivalent kilogram-force meters.",
    math: "\\tau_{(\\text{kgf·m})} = \\frac{\\tau_{(\\text{N·m})}}{9.80665} = \\tau_{(\\text{N·m})} \\times 0.10197162",
    subtext: "To convert kgf·m back to N·m, multiply the kgf·m value by 9.80665."
  },
  formulaTitle: "N·m to kgf·m Conversion Formula",
  practicalTip: {
    title: "Quick Shop Floor Estimation",
    text: "To quickly estimate kgf·m from N·m in your head: divide by 10 and add 2% (e.g., 250 N·m ÷ 10 = 25; 25 + 0.5 = 25.5 kgf·m; exact is 25.49 kgf·m)."
  },
  expertNote: {
    title: "Mass (kg) vs Gravitational Force (kgf)",
    text: "Never confuse a kilogram of mass with a kilogram of force. A kilogram is a mass unit; kilogram-force (kgf) is the gravitational force acting on that mass on Earth (9.80665 N). In older Japanese manuals, kgf·m is frequently abbreviated simply as 'kg·m' or 'm·kg'."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Classic JDM Sports Car Engine Torque",
        subtitle: "A modern dynamometer tests a turbocharged engine at 392 N·m. Convert this to kgf·m for a vintage Japanese workshop manual.",
        steps: [
          "Record initial metric value: 392 N·m.",
          "Apply conversion formula: kgf·m = 392 ÷ 9.80665.",
          "Calculate: 392 ÷ 9.80665 = 39.9729.",
          "Final Result: 392 N·m equals approximately 40.0 kgf·m (or 40.0 m·kg)."
        ]
      },
      {
        title: "Example 2: Industrial Crane Winch Braking Torque",
        subtitle: "Convert a bridge crane safety brake rating of 2,450 N·m into kilogram-force meters.",
        steps: [
          "Identify target torque: 2,450 N·m.",
          "Divide by 9.80665: 2,450 ÷ 9.80665 = 249.8305.",
          "Final Result: 2,450 N·m converts to 249.83 kgf·m."
        ]
      },
      {
        title: "Example 3: Heavy Truck Suspension Arm Bolt",
        subtitle: "A commercial chassis fastener specifies 580 N·m. Determine the equivalent kgf·m torque.",
        steps: [
          "Starting value: 580 N·m.",
          "Multiply by 0.10197162: 580 × 0.10197162 = 59.1435.",
          "Final Result: 580 N·m equals 59.14 kgf·m."
        ]
      }
    ]
  },
  table: {
    title: "Newton-Meter to Kilogram-Force Meter Reference Table",
    headers: ["Newton-Meters (N·m)", "Kilogram-Force Meters (kgf·m)", "Mechanical & Industrial Application"],
    rows: [
      { fromVal: "10 N·m", toVal: "1.02 kgf·m", extra: "Motorcycle oil filter & small cover bolts" },
      { fromVal: "20 N·m", toVal: "2.04 kgf·m", extra: "Spark plugs & small manifold bolts" },
      { fromVal: "50 N·m", toVal: "5.10 kgf·m", extra: "Automotive brake caliper mounting bolts" },
      { fromVal: "100 N·m", toVal: "10.20 kgf·m", extra: "Standard passenger car wheel lug nuts" },
      { fromVal: "150 N·m", toVal: "15.30 kgf·m", extra: "Cylinder head bolts (intermediate pass)" },
      { fromVal: "200 N·m", toVal: "20.39 kgf·m", extra: "Flywheel mounting bolts to crankshaft" },
      { fromVal: "300 N·m", toVal: "30.59 kgf·m", extra: "Front wheel hub axle nut (FWD vehicles)" },
      { fromVal: "400 N·m", toVal: "40.79 kgf·m", extra: "Midsize diesel engine peak torque" },
      { fromVal: "500 N·m", toVal: "50.99 kgf·m", extra: "Industrial planetary gearbox input shaft" },
      { fromVal: "750 N·m", toVal: "76.48 kgf·m", extra: "High-power construction equipment hydraulic motor" },
      { fromVal: "1,000 N·m", toVal: "101.97 kgf·m", extra: "Heavy industrial mining truck wheel studs" },
      { fromVal: "2,000 N·m", toVal: "203.94 kgf·m", extra: "Large marine engine crankshaft journal bolts" }
    ]
  },
  applications: {
    title: "Key Engineering Applications",
    items: [
      {
        title: "Japanese & Korean Automotive Documentation",
        text: "Automotive technical documents and OEM factory repair manuals published before the widespread adoption of pure SI units in Asia frequently specify engine output and fastener torque in kgf·m (or m·kg)."
      },
      {
        title: "Civil Construction & Heavy Mobile Cranes",
        text: "Overhead gantry and mobile telescoping crane capacity load charts in metric territories often express maximum allowable slewing and overturning moments in ton-force meters or kilogram-force meters."
      },
      {
        title: "Hydraulic Presses & Structural Jacking",
        text: "Hydraulic actuators and mechanical screw jacks calibrated with force-gauge load cells represent rotational driving torque directly in kgf·m."
      },
      {
        title: "Maritime Engine Maintenance",
        text: "Commercial shipping propulsion engines and marine diesel generators often retain legacy kgf·m torque markings on oversized hydraulic bolt tensioning tools."
      }
    ]
  },
  pitfalls: {
    title: "Important Engineering Pitfalls",
    items: [
      "Assuming 1 kgf·m = 10 N·m: While dividing by 10 gives a quick estimate, using 10 instead of 9.80665 introduces a 2.0% error, which can exceed calibration tolerances on critical engine fasteners.",
      "Confusing kgf·m with kgf·cm: 1 kgf·m = 100 kgf·cm. Setting a tool to 10 kgf·m when 10 kgf·cm was required will apply 100 times the intended torque, instantly destroying the bolt.",
      "Symbol Ambiguity (kg·m vs kgf·m): Non-technical literature often drops the 'f', writing 'kg·m'. Always verify whether the context denotes rotational torque (moment of force) or a dynamic mass moment.",
      "Ignoring Local Gravity in Calibration: Kilogram-force is defined strictly at standard Earth gravity ($9.80665\\text{ m/s}^2$), making conversion exact regardless of local laboratory elevation."
    ]
  },
  faqs: [
    {
      question: "How do I convert N·m to kgf·m?",
      answer: "Divide the Newton-meter (N·m) value by 9.80665. For example, 150 N·m ÷ 9.80665 = 15.30 kgf·m."
    },
    {
      question: "What is 100 N·m in kgf·m?",
      answer: "100 N·m equals approximately 10.20 kgf·m (100 ÷ 9.80665 = 10.1972 kgf·m)."
    },
    {
      question: "What is the difference between N·m and kgf·m?",
      answer: "A Newton-meter is the SI standard unit of torque based on the Newton (mass × acceleration). A kilogram-force meter is a gravitational metric unit based on the downward force of 1 kg mass under standard Earth gravity (1 kgf = 9.80665 N). Thus, 1 kgf·m = 9.80665 N·m."
    },
    {
      question: "Is kg·m the same as kgf·m in car manuals?",
      answer: "Yes. In Japanese, Korean, and older European automotive workshop manuals, 'kg·m' or 'm·kg' is an informal abbreviation for kilogram-force meter (kgf·m)."
    },
    {
      question: "How do I convert kgf·m back to Newton-meters?",
      answer: "Multiply the kgf·m value by 9.80665. For instance, 25 kgf·m × 9.80665 = 245.17 N·m."
    },
    {
      question: "How many kgf·m is 1 pound-foot?",
      answer: "1 pound-foot (lb·ft) equals approximately 0.138255 kgf·m (1.355818 N·m ÷ 9.80665 = 0.138255 kgf·m)."
    },
    {
      question: "Why was kgf·m largely replaced by N·m?",
      answer: "International standardization under the SI system phased out gravitational units because kgf relied on the Earth's gravitational acceleration, whereas the Newton is universally defined through fundamental physical constants."
    },
    {
      question: "What is 50 N·m in kgf·m?",
      answer: "50 N·m equals approximately 5.10 kgf·m (50 ÷ 9.80665 = 5.0986 kgf·m)."
    }
  ],
  relatedList: [
    { label: "Pound-Foot to Kilogram-Force Meter", from: "pound-foot", to: "kilogram-force-meter" },
    { label: "Newton-Meter to Pound-Foot", from: "newton-meter", to: "pound-foot" },
    { label: "Newton-Meter to Newton-Centimeter", from: "newton-meter", to: "newton-centimeter" },
    { label: "Newton-Meter to Dyne-Centimeter", from: "newton-meter", to: "dyne-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Pound-Foot to Kilogram-Force Meter Conversion Guide",
      description: "Convert US customary automotive torque specs into metric gravitational units.",
      from: "pound-foot",
      to: "kilogram-force-meter"
    },
    {
      title: "Newton-Meter to Pound-Foot Conversion Guide",
      description: "Standard metric to imperial torque calculations for automotive and mechanical systems.",
      from: "newton-meter",
      to: "pound-foot"
    }
  ],
  references: [
    "BIPM: The International System of Units (SI Brochure, 9th Edition)",
    "ISO 80000-4: Quantities and Units — Mechanics",
    "JIS B 0151: Iron and Steel Fastener Tightening Specifications",
    "DIN 1305: Mass, Weight Value, Force, Weight Force (German Institute for Standardization)"
  ]
};
