import { CustomArticleData } from "./types";

export const poundFootToKilogramForceMeter: CustomArticleData = {
  fromUnitId: "pound-foot",
  toUnitId: "kilogram-force-meter",
  seoTitle: "Pound-Foot to Kilogram-Force Meter Converter (lb·ft to kgf·m)",
  metaDescription: "Convert pound-feet to kilogram-force meters (lb·ft to kgf·m) accurately. Formula, 0.138255 factor, JDM and industrial machinery examples, tables, and FAQs.",
  h1: "Pound-Foot to Kilogram-Force Meter Converter",
  introduction: [
    "The pound-foot (lb·ft, or foot-pound) and the kilogram-force meter (kgf·m, also written as m·kg or meter-kilogram) are rotational torque units representing the imperial and gravitational metric systems, respectively. While the pound-foot is the standard torque measurement across North American automotive and industrial manufacturing, the kilogram-force meter is widely used in legacy Asian (especially Japanese Domestic Market / JDM) vehicle manuals, crane load charts, and international shipping machinery.",
    "Converting pound-feet to kilogram-force meters bridges American mechanical engineering with gravitational metric service literature. Because 1 pound-force equals 4.4482216152605 Newtons, 1 foot equals 0.3048 meters, and standard Earth gravity is exactly 9.80665 m/s², one pound-foot equals exactly $1.3558179483314 / 9.80665 \\approx 0.1382549544\\text{ kgf·m}$. Converting from lb·ft to kgf·m requires multiplying by approximately 0.138255 (or dividing by 7.233014).",
    "This technical guide covers the physical principles of both torque units, provides worked conversion examples for automotive engine tuning and crane lifting, presents a clear reference table, and resolves common mechanical maintenance questions."
  ],
  quickAnswer: {
    text: "To convert pound-feet to kilogram-force meters, multiply the value by 0.138255 (or divide by 7.233014). For example, an engine producing 300 lb·ft of torque develops approximately 41.48 kgf·m (or 41.5 m·kg) of rotational effort.",
    formulaDisplay: "\\text{kgf·m} = \\text{lb·ft} \\times 0.138255",
    subtext: "1 pound-foot equals approximately 0.138255 kilogram-force meters (kgf·m)."
  },
  aboutSourceUnit: {
    title: "Understanding the Pound-Foot (lb·ft)",
    text: "The pound-foot (symbol: lb·ft or lbf·ft) is the US customary and imperial unit of torque. It quantifies the rotational moment produced by one pound of force exerted perpendicular to a one-foot radial arm (1 lb·ft = 1 lbf × 1 ft = 1.355818 N·m). It is the standard rating for American passenger cars, commercial diesel trucks, and construction equipment."
  },
  aboutTargetUnit: {
    title: "Understanding the Kilogram-Force Meter (kgf·m)",
    text: "The kilogram-force meter (symbol: kgf·m, m·kgf, or m·kg) is a gravitational metric unit of torque. It represents the moment generated by the gravitational force of a one-kilogram mass (9.80665 N) applied at a one-meter lever arm (1 kgf·m = 1 kgf × 1 m = 9.80665 N·m). It is standard in Japanese automotive service documentation, heavy press manufacturing, and port crane ratings."
  },
  relationship: "Derived through standard physical constants: $1\\text{ lb·ft} = \\frac{1.3558179483314\\text{ N·m}}{9.80665\\text{ N/kgf}} \\approx 0.1382549544\\text{ kgf·m}$. Conversely, $1\\text{ kgf·m} = \\frac{9.80665}{1.3558179483314} \\approx 7.23301385\\text{ lb·ft}$.",
  relationshipTitle: "Imperial to Gravitational Metric Torque Benchmark",
  relationshipItems: [
    { label: "1.0 lb·ft", value: "0.1383 kgf·m (Light bracket & lever adjustment)" },
    { label: "50 lb·ft", value: "6.913 kgf·m (Automotive suspension control arm bolts)" },
    { label: "100 lb·ft", value: "13.825 kgf·m (Standard car wheel lug nut specification)" },
    { label: "250 lb·ft", value: "34.564 kgf·m (Heavy truck crankshaft damper bolt)" },
    { label: "500 lb·ft", value: "69.127 kgf·m (High-performance diesel engine torque)" }
  ],
  formula: {
    text: "Multiply the torque in pound-feet by the conversion constant 0.13825495 to calculate the equivalent kilogram-force meters.",
    math: "\\tau_{(\\text{kgf·m})} = \\tau_{(\\text{lb·ft})} \\times 0.13825495",
    subtext: "Alternatively: Divide the pound-foot value by 7.233014."
  },
  formulaTitle: "lb·ft to kgf·m Conversion Formula",
  practicalTip: {
    title: "Quick Mental Calculation Rule",
    text: "To approximate kgf·m from lb·ft mentally: divide by 7.2 (or divide by 10 and multiply by 1.38). For example, 72 lb·ft ÷ 7.2 = 10 kgf·m (exact is 9.95 kgf·m)."
  },
  expertNote: {
    title: "JDM Workshop Manual Shorthand",
    text: "Japanese Domestic Market (JDM) repair manuals for Nissan, Toyota, Honda, and Mitsubishi vehicles from the 1980s through 2000s frequently print torque as 'kg-m' or 'm-kg' rather than 'kgf·m'. These refer to identical gravitational torque units."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: JDM Engine Dyno Comparison",
        subtitle: "An American tuner modifies a Japanese sports car engine to produce 380 lb·ft on a dyno. Convert to kgf·m.",
        steps: [
          "Identify initial torque: 380 lb·ft.",
          "Multiply by conversion factor: kgf·m = 380 × 0.13825495.",
          "Calculate: 380 × 0.13825495 = 52.5369.",
          "Final Result: 380 lb·ft converts to 52.54 kgf·m (or 52.5 m·kg)."
        ]
      },
      {
        title: "Example 2: Wheel Lug Nut Setting",
        subtitle: "Convert an 85 lb·ft lug nut specification into kilogram-force meters.",
        steps: [
          "Starting value: 85 lb·ft.",
          "Apply formula: 85 ÷ 7.233014 = 11.7517.",
          "Final Result: 85 lb·ft equals approximately 11.75 kgf·m."
        ]
      },
      {
        title: "Example 3: Heavy Excavator Hydraulic Winch",
        subtitle: "A crane winch rated at 1,200 lb·ft needs to be documented in kgf·m for an overseas client. Find the value.",
        steps: [
          "Starting value: 1,200 lb·ft.",
          "Multiply by 0.13825495: 1,200 × 0.13825495 = 165.9059.",
          "Final Result: 1,200 lb·ft equals 165.91 kgf·m."
        ]
      }
    ]
  },
  table: {
    title: "Pound-Foot to Kilogram-Force Meter Reference Table",
    headers: ["Pound-Feet (lb·ft)", "Kilogram-Force Meters (kgf·m / m·kg)", "Mechanical & Industrial Application"],
    rows: [
      { fromVal: "5 lb·ft", toVal: "0.69 kgf·m", extra: "Motorcycle lever pivots & light engine covers" },
      { fromVal: "10 lb·ft", toVal: "1.38 kgf·m", extra: "Automotive oil pan perimeter bolts" },
      { fromVal: "20 lb·ft", toVal: "2.77 kgf·m", extra: "Spark plugs in aluminum heads" },
      { fromVal: "35 lb·ft", toVal: "4.84 kgf·m", extra: "Brake caliper bracket mounting bolts" },
      { fromVal: "50 lb·ft", toVal: "6.91 kgf·m", extra: "Camshaft sprocket bolts & suspension links" },
      { fromVal: "75 lb·ft", toVal: "10.37 kgf·m", extra: "Compact car wheel lug nuts" },
      { fromVal: "90 lb·ft", toVal: "12.44 kgf·m", extra: "Midsize sedan wheel lug nuts" },
      { fromVal: "100 lb·ft", toVal: "13.83 kgf·m", extra: "Standard automotive wheel lug nut spec" },
      { fromVal: "150 lb·ft", toVal: "20.74 kgf·m", extra: "Crankshaft damper pulley bolt" },
      { fromVal: "250 lb·ft", toVal: "34.56 kgf·m", extra: "Front drive axle spindle nut" },
      { fromVal: "400 lb·ft", toVal: "55.30 kgf·m", extra: "V8 performance engine peak torque" },
      { fromVal: "600 lb·ft", toVal: "82.95 kgf·m", extra: "Heavy commercial turbo-diesel truck engine" },
      { fromVal: "1,000 lb·ft", toVal: "138.25 kgf·m", extra: "Heavy industrial mining & construction equipment" }
    ]
  },
  applications: {
    title: "Key Automotive & Industrial Uses",
    items: [
      {
        title: "Japanese Import & JDM Vehicle Tuning",
        text: "Automotive enthusiasts and racing technicians importing classic sports cars (Skyline, Supra, RX-7) convert factory service torque figures between US customary lb·ft and OEM kgf·m manuals."
      },
      {
        title: "Heavy Mobile Cranes & Winches",
        text: "Offshore maritime winches and telescoping mobile crane slewing gearboxes manufactured in Asia often display capacity ratings in metric ton-meters and kgf·m."
      },
      {
        title: "Industrial Hydraulic Presses",
        text: "Machine tool manufacturers converting US technical documentation for Asian markets express hydraulic rotary actuator limits in kgf·m."
      },
      {
        title: "Marine Diesel Engine Overhaul",
        text: "Naval engineers and ship mechanics use hydraulic bolt tensioning gear calibrated in both imperial foot-pounds and gravitational metric kgf·m."
      }
    ]
  },
  pitfalls: {
    title: "Common Conversion Mistakes to Avoid",
    items: [
      "Confusing kgf·m with kgf·cm: 1 kgf·m equals 100 kgf·cm. Setting a tool to 10 kgf·m when 10 kgf·cm was required applies 100 times too much torque, snapping the bolt instantly.",
      "Dividing by 0.13825 Instead of Multiplying: Dividing by 0.13825 inflates the torque by over 7 times, leading to severe component damage.",
      "Ignoring Fastener Plating / Lubrication: Conversion calculates dry torque. If using molybdenum assembly lube or threadlocker, reduce target torque by 20% to 30% to avoid over-stretching the fastener.",
      "Treating kgf·m as SI Units: The kgf·m is a gravitational unit, not a pure SI unit. In modern international contracts, ensure specifications are officially converted to SI Newton-meters (N·m)."
    ]
  },
  faqs: [
    {
      question: "How do I convert pound-feet to kilogram-force meters?",
      answer: "Multiply the pound-foot (lb·ft) value by 0.138255 (or divide by 7.233014). For example, 100 lb·ft × 0.138255 = 13.83 kgf·m."
    },
    {
      question: "What is 100 lb·ft in kgf·m?",
      answer: "100 lb·ft equals approximately 13.83 kgf·m (or 13.83 m·kg)."
    },
    {
      question: "How many lb·ft are in 1 kgf·m?",
      answer: "1 kilogram-force meter (kgf·m) equals approximately 7.233014 pound-feet (lb·ft)."
    },
    {
      question: "Is m·kg the same as kgf·m in Japanese car manuals?",
      answer: "Yes, 'm·kg', 'kg·m', and 'kgf·m' are identical abbreviations used in Japanese and international automotive technical literature for kilogram-force meter."
    },
    {
      question: "What is 300 lb·ft in kgf·m?",
      answer: "300 lb·ft equals approximately 41.48 kgf·m (300 × 0.138255 = 41.4765 kgf·m)."
    },
    {
      question: "How do I convert kgf·m back to lb·ft?",
      answer: "Multiply the kgf·m value by 7.233014 (or divide by 0.138255). For example, 40 kgf·m × 7.233014 = 289.32 lb·ft."
    },
    {
      question: "What is 80 lb·ft in kgf·m?",
      answer: "80 lb·ft equals approximately 11.06 kgf·m (80 × 0.138255 = 11.0604 kgf·m)."
    },
    {
      question: "Why do Japanese manuals use kgf·m instead of N·m?",
      answer: "Older Japanese engineering standards (JIS) relied on the gravitational metric system (MKS). While modern Japanese manufacturers use SI Newton-meters, legacy documentation and racing literature retain kgf·m."
    }
  ],
  relatedList: [
    { label: "Kilogram-Force Meter to Pound-Foot", from: "kilogram-force-meter", to: "pound-foot" },
    { label: "Newton-Meter to Kilogram-Force Meter", from: "newton-meter", to: "kilogram-force-meter" },
    { label: "Pound-Foot to Newton-Meter", from: "pound-foot", to: "newton-meter" },
    { label: "Pound-Foot to Pound-Inch", from: "pound-foot", to: "pound-inch" }
  ],
  relatedArticles: [
    {
      title: "Newton-Meter to Kilogram-Force Meter Conversion Guide",
      description: "Convert SI metric torque into gravitational metric units for Japanese domestic market engines.",
      from: "newton-meter",
      to: "kilogram-force-meter"
    },
    {
      title: "Pound-Foot to Newton-Meter Conversion Guide",
      description: "Convert imperial foot-pounds into SI Newton-meters for international automotive specifications.",
      from: "pound-foot",
      to: "newton-meter"
    }
  ],
  references: [
    "JIS B 0151: Iron and Steel Fastener Tightening Specifications (Japanese Standards Association)",
    "ISO 80000-4: Quantities and Units — Part 4: Mechanics",
    "SAE J1701: Torque-Tension Relationship for Threaded Fasteners",
    "NIST Special Publication 811: Guide for the Use of the International System of Units"
  ]
};
