import { CustomArticleData } from "./types";

export const poundInchToNewtonMeter: CustomArticleData = {
  fromUnitId: "pound-inch",
  toUnitId: "newton-meter",
  seoTitle: "Pound-Inch to Newton-Meter Converter (lb·in to N·m)",
  metaDescription: "Convert pound-inches to Newton-meters (lb·in to N·m) with precise formulas, 0.1129848 factor, step-by-step calculations, fastener torque charts, and FAQs.",
  canonicalUrl: "https://unitsconvertors.com/pound-inch-to-newton-meter",
  h1: "Pound-Inch to Newton-Meter Converter",
  introduction: [
    "The pound-inch (symbol: lb·in, commonly written in industry as in-lb or inch-pound) and the Newton-meter (symbol: N·m) are two standard units of rotational torque used to specify fastener tightness and shaft torsion. While the pound-inch remains the standard unit across North American aerospace manufacturing, precision electronics, cycling mechanics, and firearm assembly, the Newton-meter serves as the official derived unit of torque in the International System of Units (SI).",
    "Converting pound-inches to Newton-meters is a daily task for technicians working with metric blueprints or foreign machinery. Because one international pound-foot equals exactly 1.3558179483314 Newton-meters, dividing this value across 12 inches establishes that 1 pound-inch equals exactly 0.1129848290276167 N·m. Conversely, 1 Newton-meter equals approximately 8.85074579 pound-inches.",
    "This technical guide details the conversion formulas, presents clear manual calculation steps, highlights realistic mechanical engineering examples, provides a precision torque table, and answers common trade questions regarding torque tool calibration."
  ],
  quickAnswer: {
    text: "To convert pound-inches to Newton-meters, multiply the torque value by 0.1129848 (or divide by 8.850746). For example, a bicycle stem bolt tightened to 50 lb·in equals approximately 5.65 N·m.",
    formulaDisplay: "\\text{N·m} = \\text{lb·in} \\times 0.1129848",
    subtext: "1 pound-inch equals exactly 0.112984829 N·m, while 1 N·m equals approximately 8.850746 lb·in."
  },
  aboutSourceUnit: {
    title: "Understanding the Pound-Inch (lb·in)",
    text: "The pound-inch (symbol: lb·in or in-lb) is an imperial and US customary unit of torque. It measures the rotational moment produced by one pound-force acting perpendicularly at the end of a one-inch radius lever arm (1 lb·in = 1 lbf × 1 in). It is the preferred unit for low-torque assemblies where foot-pounds would produce awkwardly small decimals, such as printed circuit board mounting, intake manifold flanges, and small internal combustion components."
  },
  aboutTargetUnit: {
    title: "Understanding the Newton-Meter (N·m)",
    text: "The Newton-meter (symbol: N·m) is the coherent SI unit of torque or rotational moment. One Newton-meter corresponds to the torque generated by a perpendicular force of one Newton applied at a displacement radius of one meter (1 N·m = 1 N × 1 m). From micro-fasteners in consumer electronics to massive structural bolts on wind turbines, the Newton-meter is the standard torque metric across international industry and academic physics."
  },
  relationship: "The relationship between pound-inches and Newton-meters stems directly from the international definitions of the pound-force (4.4482216152605 N) and the international inch (0.0254 m). Multiplying these two constants gives: 1 lb·in = 4.4482216152605 N × 0.0254 m = 0.1129848290276167 N·m. Dividing 1 by this constant yields the inverse conversion: 1 N·m ≈ 8.85074579 lb·in.",
  relationshipTitle: "Torque Scale Equivalencies (lb·in vs N·m)",
  relationshipItems: [
    { label: "10 lb·in", value: "1.13 N·m (Small electronic enclosure & carburetor jet screws)" },
    { label: "25 lb·in", value: "2.82 N·m (Rifle scope mounting rings & instrument panels)" },
    { label: "50 lb·in", value: "5.65 N·m (Bicycle handlebar stem faceplates & M5 carbon components)" },
    { label: "100 lb·in", value: "11.30 N·m (Automotive transmission pan & valve cover perimeter bolts)" },
    { label: "150 lb·in", value: "16.95 N·m (Small engine cylinder head bolts & water pump housings)" },
    { label: "250 lb·in", value: "28.25 N·m (Automotive spark plugs & hydraulic line fittings)" }
  ],
  formula: {
    text: "Multiply the torque value in pound-inches by 0.1129848 to calculate the equivalent torque in Newton-meters.",
    math: "\\tau_{(\\text{N·m})} = \\tau_{(\\text{lb·in})} \\times 0.1129848",
    subtext: "Alternatively: Divide the pound-inch value by 8.850746."
  },
  formulaTitle: "Pound-Inch to Newton-Meter Conversion Formula",
  practicalTip: {
    title: "Quick Mental Estimation",
    text: "For quick shop estimates when a calculator is not accessible, divide the pound-inch value by 9 (since 1 / 8.85 ≈ 0.113). For example, 45 lb·in / 9 ≈ 5 N·m (the exact value is 5.08 N·m, giving an error of less than 2%)."
  },
  expertNote: {
    title: "Never Confuse Pound-Inches with Foot-Pounds",
    text: "Torque wrenches marked in foot-pounds operate at 12 times the magnitude of inch-pound wrenches. Setting a foot-pound torque wrench to 50 for a bolt specified at 50 lb·in delivers 600 lb·in (67.8 N·m), which will instantly strip threads, snap the fastener, or crack aluminum castings."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Carbon Bicycle Handlebar Stem Clamp",
        subtitle: "A component manufacturer recommends a maximum tightening torque of 45 lb·in for an M5 stem bolt. Convert this limit to Newton-meters.",
        steps: [
          "Identify the given torque: 45 lb·in.",
          "Apply the conversion formula: N·m = lb·in × 0.1129848.",
          "Perform the calculation: 45 × 0.1129848 = 5.084316 N·m.",
          "Round to an appropriate shop tolerance: 5.08 N·m (set a metric torque wrench to 5.1 N·m)."
        ]
      },
      {
        title: "Example 2: Precision Rifle Scope Ring Screws",
        subtitle: "An optics mounting guide specifies 15 lb·in on Torx T15 screws. Convert to N·m to calibrate a European torque screwdriver.",
        steps: [
          "Starting value: 15 lb·in.",
          "Multiply by 0.1129848: 15 × 0.1129848 = 1.694772 N·m.",
          "Final Result: 15 lb·in corresponds to 1.69 N·m (approximately 1.7 N·m)."
        ]
      },
      {
        title: "Example 3: Automotive Transmission Fluid Pan Bolts",
        subtitle: "A service manual lists a tightening specification of 108 lb·in for transmission pan bolts. Determine the torque in N·m.",
        steps: [
          "Starting value: 108 lb·in.",
          "Multiply by 0.1129848: 108 × 0.1129848 = 12.202358 N·m.",
          "Final Result: 108 lb·in equals approximately 12.20 N·m (or 9.0 lb·ft)."
        ]
      }
    ]
  },
  table: {
    title: "Pound-Inch to Newton-Meter Conversion Reference Table",
    headers: ["Pound-Inches (lb·in / in-lb)", "Newton-Meters (N·m)", "Foot-Pound Equivalent", "Common Engineering Application"],
    rows: [
      { fromVal: "5 lb·in", toVal: "0.56 N·m", extra: "0.42 lb·ft", extra2: "Precision electronics M2.5 screws" },
      { fromVal: "10 lb·in", toVal: "1.13 N·m", extra: "0.83 lb·ft", extra2: "Electrical terminal strip screws" },
      { fromVal: "15 lb·in", toVal: "1.69 N·m", extra: "1.25 lb·ft", extra2: "Firearm scope ring Torx screws" },
      { fromVal: "20 lb·in", toVal: "2.26 N·m", extra: "1.67 lb·ft", extra2: "Rifle action screws (synthetic stocks)" },
      { fromVal: "25 lb·in", toVal: "2.82 N·m", extra: "2.08 lb·ft", extra2: "Carburetor fuel bowl screws" },
      { fromVal: "30 lb·in", toVal: "3.39 N·m", extra: "2.50 lb·ft", extra2: "Bicycle disc brake rotor M5 Torx bolts" },
      { fromVal: "40 lb·in", toVal: "4.52 N·m", extra: "3.33 lb·ft", extra2: "Bicycle brake lever bar clamps" },
      { fromVal: "50 lb·in", toVal: "5.65 N·m", extra: "4.17 lb·ft", extra2: "Stem faceplate 4-bolt clamp hardware" },
      { fromVal: "60 lb·in", toVal: "6.78 N·m", extra: "5.00 lb·ft", extra2: "Seatpost collar clamp (aluminum frames)" },
      { fromVal: "75 lb·in", toVal: "8.47 N·m", extra: "6.25 lb·ft", extra2: "Valve cover perimeter bolts" },
      { fromVal: "90 lb·in", toVal: "10.17 N·m", extra: "7.50 lb·ft", extra2: "Automotive engine thermostat housing" },
      { fromVal: "100 lb·in", toVal: "11.30 N·m", extra: "8.33 lb·ft", extra2: "Transmission oil pan flange bolts" },
      { fromVal: "120 lb·in", toVal: "13.56 N·m", extra: "10.00 lb·ft", extra2: "Motorcycle engine side case covers" },
      { fromVal: "150 lb·in", toVal: "16.95 N·m", extra: "12.50 lb·ft", extra2: "Water pump pulley attachment bolts" },
      { fromVal: "200 lb·in", toVal: "22.60 N·m", extra: "16.67 lb·ft", extra2: "Spark plugs in aluminum cylinder heads" }
    ]
  },
  applications: {
    title: "Key Industry & Trade Applications",
    items: [
      {
        title: "Bicycle Manufacturing & Shop Maintenance",
        text: "Modern road and cross-country bicycles make extensive use of carbon-fiber composites and thin-walled aluminum tubing. Torque limits on stem faceplates, seatpost collars, and disc calipers are strictly enforced between 30 and 70 lb·in (3.4 to 7.9 N·m) to prevent structural crush."
      },
      {
        title: "Precision Firearms & Hunting Optics",
        text: "Mounting telescopic sights to rifle receivers requires tight adherence to inch-pound torque ratings. Over-torquing ring screws can bind internal magnification lenses, while under-torquing causes reticle shift under heavy recoil."
      },
      {
        title: "Aerospace Avionics & Cabin Systems",
        text: "Aircraft maintenance manuals specify torque in pound-inches for electrical connectors, instrument cluster mounting, and access panels. Technicians routinely convert between imperial blueprint values and European metric torque tools."
      },
      {
        title: "Automotive Gasket & Stamped Pan Fastening",
        text: "Engine oil pans, transmission covers, and valve covers utilize silicone or rubber gaskets sealed by dozens of small M6 fasteners. Torque is specified in pound-inches to prevent gasket extrusion and uneven sealing."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes to Avoid",
    items: [
      "Confusing pound-inches with pound-feet: 1 lb·ft equals 12 lb·in. Applying 40 lb·ft instead of 40 lb·in applies 480 lb·in (54.2 N·m), inevitably shearing the fastener.",
      "Using the wrong section of a torque wrench scale: Mechanical click wrenches are most accurate between 20% and 100% of their rated capacity. Never use a 10–100 lb·ft wrench to measure 5 lb·ft (60 lb·in).",
      "Ignoring dry versus lubricated thread conditions: Torque specifications assume clean, dry threads unless anti-seize or threadlocker is explicitly noted. Lubricants can increase bolt tension by 30% to 50% at the same indicated torque.",
      "Neglecting torque driver calibration: Spring-loaded inch-pound drivers lose calibration if stored under tension. Always dial the tool back to its lowest setting after completing work."
    ]
  },
  faqs: [
    {
      question: "How do I convert pound-inches to Newton-meters?",
      answer: "Multiply the pound-inch value by 0.1129848. For example, 50 lb·in × 0.1129848 = 5.65 N·m. Alternatively, divide the pound-inch value by 8.850746."
    },
    {
      question: "Is pound-inch identical to inch-pound?",
      answer: "Yes, 'pound-inch' (lb·in) and 'inch-pound' (in-lb) are interchangeable terms representing the same physical quantity of torque. Formal engineering style guides prefer lb·in to distinguish torque from energy, but in-lb is standard on tool dials."
    },
    {
      question: "What is 40 inch-pounds in Newton-meters?",
      answer: "40 in-lb equals 4.52 N·m (40 × 0.1129848 = 4.5194 N·m). This is a common torque limit for bicycle handlebar faceplates."
    },
    {
      question: "How many Newton-meters are in 1 pound-inch?",
      answer: "There are exactly 0.112984829 Newton-meters in 1 pound-inch. Conversely, 1 Newton-meter equals 8.850746 pound-inches."
    },
    {
      question: "Why do low-torque fasteners use pound-inches instead of foot-pounds?",
      answer: "Small fasteners (M3 through M6) require low torque values that would appear as fractions or decimals in foot-pounds (for example, 24 lb·in is only 2.0 lb·ft). Using pound-inches provides whole numbers that are easier to set accurately on precision tools."
    },
    {
      question: "What is 100 in-lb in N·m?",
      answer: "100 in-lb equals 11.30 N·m (100 × 0.1129848 = 11.2985 N·m). In foot-pounds, 100 in-lb equals 8.33 lb·ft."
    },
    {
      question: "Can I use a foot-pound torque wrench to tighten pound-inch bolts?",
      answer: "Only if the wrench has an extremely low range that covers the value. Standard 3/8-inch or 1/2-inch drive foot-pound wrenches cannot accurately register low torque values below 10–15 lb·ft (120–180 lb·in). Use a dedicated 1/4-inch drive inch-pound torque wrench."
    },
    {
      question: "How do I convert N·m back to lb·in?",
      answer: "Multiply the Newton-meter value by 8.850746. For example, 10 N·m × 8.850746 = 88.51 lb·in."
    }
  ],
  relatedList: [
    { label: "Newton-Meter to Pound-Inch", from: "newton-meter", to: "pound-inch" },
    { label: "Pound-Inch to Pound-Foot", from: "pound-inch", to: "pound-foot" },
    { label: "Pound-Inch to Newton-Centimeter", from: "pound-inch", to: "newton-centimeter" },
    { label: "Pound-Inch to Kilogram-Force Meter", from: "pound-inch", to: "kilogram-force-meter" }
  ],
  relatedArticles: [
    {
      title: "Newton-Meter to Pound-Inch Conversion Guide",
      description: "Step-by-step conversion factors, metric bolt limits, and precision torque wrench calibration.",
      from: "newton-meter",
      to: "pound-inch"
    },
    {
      title: "Pound-Foot to Pound-Inch Conversion Guide",
      description: "Learn how to convert between large vehicle torque specifications and precision assembly values.",
      from: "pound-foot",
      to: "pound-inch"
    }
  ],
  references: [
    "ASME B107.300: Manual Torque Instruments and Calibration Procedures",
    "ISO 6789-1: Assembly tools for screws and nuts — Hand torque tools",
    "NIST Special Publication 811: Guide for the Use of the International System of Units",
    "SAE J2270: Applications for Threaded Fasteners in Fluid Power Systems"
  ]
};
