import { CustomArticleData } from "./types";

export const poundInchToKilogramForceMeter: CustomArticleData = {
  fromUnitId: "pound-inch",
  toUnitId: "kilogram-force-meter",
  seoTitle: "Pound-Inch to Kilogram-Force Meter Converter (lb·in to kgf·m)",
  metaDescription: "Convert pound-inches to kilogram-force meters (lb·in to kgf·m) accurately. Formula, 0.0115212 factor, step-by-step calculations, torque tables, and FAQs.",
  canonicalUrl: "https://unitsconvertors.com/pound-inch-to-kilogram-force-meter",
  h1: "Pound-Inch to Kilogram-Force Meter Converter",
  introduction: [
    "The pound-inch (symbol: lb·in, widely denoted as in-lb or inch-pound) and the kilogram-force meter (symbol: kgf·m or m·kg) represent two distinct measurement traditions in mechanical engineering. The pound-inch is the prevailing US customary torque unit for delicate fasteners, while the kilogram-force meter is a legacy gravitational metric unit widely encountered in Japanese (JIS), European, and Latin American industrial service manuals, classic motorcycle specifications, and marine machinery blueprints.",
    "Converting pound-inches to kilogram-force meters bridges North American low-torque fasteners with gravitational metric equipment standards. Because 1 kilogram-force meter equals exactly 9.80665 Newton-meters and 1 pound-inch equals 0.112984829 Newton-meters, dividing the two constants shows that 1 pound-inch equals approximately 0.0115212 kilogram-force meters (or 1 kgf·m ≈ 86.7962 lb·in).",
    "This technical guide details the gravitational conversion formulas, explains how to convert small decimal values safely, provides practical workshop calculations for vintage Japanese and European machinery, and offers a comprehensive reference table."
  ],
  quickAnswer: {
    text: "To convert pound-inches to kilogram-force meters, multiply the torque value by 0.0115212 (or divide by 86.7962). For example, a motorcycle engine cover bolt tightened to 87 lb·in converts to approximately 1.00 kgf·m.",
    formulaDisplay: "\\text{kgf·m} = \\text{lb·in} \\times 0.0115212",
    subtext: "1 kilogram-force meter equals approximately 86.7962 pound-inches. 1 pound-inch equals 0.0115212 kgf·m."
  },
  aboutSourceUnit: {
    title: "Understanding the Pound-Inch (lb·in)",
    text: "The pound-inch (symbol: lb·in or in-lb) is an imperial unit of torque defined as the rotational moment generated by one pound-force acting at a perpendicular distance of one inch (1 lb·in = 1 lbf × 1 in). It is standard in American aerospace assembly, small-engine overhaul, bicycle repair, and firearms gunsmithing where torque levels are too low to be conveniently expressed in foot-pounds."
  },
  aboutTargetUnit: {
    title: "Understanding the Kilogram-Force Meter (kgf·m)",
    text: "The kilogram-force meter (symbol: kgf·m, also written as m·kg or kg·m) is a gravitational metric unit of torque. It represents the rotational force produced when a mass of one kilogram is accelerated by standard Earth gravity (9.80665 m/s²) at a radius of one meter (1 kgf·m = 9.80665 N·m). Though superseded by the SI Newton-meter in modern ISO standards, kgf·m remains prominent on legacy Japanese machine tools, older automotive workshop manuals, and heavy Asian industrial equipment."
  },
  relationship: "The relationship between pound-inches and kilogram-force meters combines imperial force-distance definitions with standard gravitational acceleration: 1 pound-force is 4.448222 N, 1 inch is 0.0254 m, making 1 lb·in = 0.11298483 N·m. Because 1 kgf·m is defined as exactly 9.80665 N·m, 1 lb·in = 0.11298483 / 9.80665 = 0.011521246 kgf·m. Inverting this factor gives 1 kgf·m = 9.80665 / 0.11298483 ≈ 86.796166 lb·in.",
  relationshipTitle: "Torque Scale Equivalencies (lb·in vs kgf·m)",
  relationshipItems: [
    { label: "10 lb·in", value: "0.115 kgf·m (Small electronic enclosure screws)" },
    { label: "25 lb·in", value: "0.288 kgf·m (Carburetor float bowl fasteners)" },
    { label: "50 lb·in", value: "0.576 kgf·m (Bicycle handlebar stem faceplate bolts)" },
    { label: "86.8 lb·in", value: "1.000 kgf·m (Standard metric gravitational unit baseline)" },
    { label: "150 lb·in", value: "1.728 kgf·m (Small engine valve cover bolts)" },
    { label: "250 lb·in", value: "2.880 kgf·m (Motorcycle clutch spring bolts)" }
  ],
  formula: {
    text: "Multiply the torque value in pound-inches by 0.01152125 to obtain the torque in kilogram-force meters.",
    math: "\\tau_{(\\text{kgf·m})} = \\tau_{(\\text{lb·in})} \\times 0.01152125",
    subtext: "Alternatively: Divide the pound-inch value by 86.79617."
  },
  formulaTitle: "Pound-Inch to Kilogram-Force Meter Conversion Formula",
  practicalTip: {
    title: "Centimeter-Kilogram Intermediate Conversion",
    text: "Many older Japanese motorcycle manuals specify low torque in kgf·cm (kilogram-force centimeters) rather than kgf·m. Because 1 m = 100 cm, 1 kgf·m = 100 kgf·cm. Therefore, 1 lb·in = 1.152 kgf·cm. To get kgf·cm from lb·in, simply multiply by 1.15."
  },
  expertNote: {
    title: "Beware of kgf·m vs N·m Confusion",
    text: "A kilogram-force meter is nearly ten times larger than a Newton-meter (1 kgf·m = 9.81 N·m). When reading older imported shop manuals, ensure you do not mistake kgf·m for N·m, as tightening an 87 lb·in bolt to 87 N·m (770 lb·in) will instantly snap the fastener."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Vintage Japanese Motorcycle Crankcase Cover",
        subtitle: "An American mechanic with an inch-pound torque wrench needs to torque bolts specified in an old manual as 0.85 kgf·m. Determine the equivalent in lb·in.",
        steps: [
          "Identify target value: 0.85 kgf·m.",
          "Use the inverse factor (86.7962): lb·in = 0.85 × 86.7962.",
          "Calculate: 0.85 × 86.7962 = 73.77677 lb·in.",
          "Final Result: 0.85 kgf·m corresponds to 73.8 lb·in (set the wrench to 74 in-lb)."
        ]
      },
      {
        title: "Example 2: Small Engine Valve Cover Bolt",
        subtitle: "A service manual specifies 65 lb·in for valve cover bolts. Convert this value to kgf·m for an international client report.",
        steps: [
          "Starting value: 65 lb·in.",
          "Apply formula: kgf·m = 65 × 0.01152125.",
          "Calculate: 65 × 0.01152125 = 0.74888 kgf·m.",
          "Final Result: 65 lb·in converts to approximately 0.75 kgf·m (or 75 kgf·cm)."
        ]
      },
      {
        title: "Example 3: Industrial Pump Seal Gland Fasteners",
        subtitle: "Convert a tightening torque of 120 lb·in into kgf·m.",
        steps: [
          "Starting value: 120 lb·in.",
          "Multiply by 0.01152125: 120 × 0.01152125 = 1.38255 kgf·m.",
          "Final Result: 120 lb·in equals approximately 1.38 kgf·m."
        ]
      }
    ]
  },
  table: {
    title: "Pound-Inch to Kilogram-Force Meter Reference Table",
    headers: ["Pound-Inches (lb·in / in-lb)", "Kilogram-Force Meters (kgf·m)", "Kilogram-Force Centimeters (kgf·cm)", "Newton-Meter Equivalent"],
    rows: [
      { fromVal: "10 lb·in", toVal: "0.115 kgf·m", extra: "11.52 kgf·cm", extra2: "1.13 N·m" },
      { fromVal: "20 lb·in", toVal: "0.230 kgf·m", extra: "23.04 kgf·cm", extra2: "2.26 N·m" },
      { fromVal: "30 lb·in", toVal: "0.346 kgf·m", extra: "34.56 kgf·cm", extra2: "3.39 N·m" },
      { fromVal: "40 lb·in", toVal: "0.461 kgf·m", extra: "46.08 kgf·cm", extra2: "4.52 N·m" },
      { fromVal: "50 lb·in", toVal: "0.576 kgf·m", extra: "57.61 kgf·cm", extra2: "5.65 N·m" },
      { fromVal: "60 lb·in", toVal: "0.691 kgf·m", extra: "69.13 kgf·cm", extra2: "6.78 N·m" },
      { fromVal: "70 lb·in", toVal: "0.806 kgf·m", extra: "80.65 kgf·cm", extra2: "7.91 N·m" },
      { fromVal: "80 lb·in", toVal: "0.922 kgf·m", extra: "92.17 kgf·cm", extra2: "9.04 N·m" },
      { fromVal: "86.8 lb·in", toVal: "1.000 kgf·m", extra: "100.00 kgf·cm", extra2: "9.81 N·m" },
      { fromVal: "100 lb·in", toVal: "1.152 kgf·m", extra: "115.21 kgf·cm", extra2: "11.30 N·m" },
      { fromVal: "120 lb·in", toVal: "1.383 kgf·m", extra: "138.25 kgf·cm", extra2: "13.56 N·m" },
      { fromVal: "150 lb·in", toVal: "1.728 kgf·m", extra: "172.82 kgf·cm", extra2: "16.95 N·m" },
      { fromVal: "180 lb·in", toVal: "2.074 kgf·m", extra: "207.38 kgf·cm", extra2: "20.34 N·m" },
      { fromVal: "200 lb·in", toVal: "2.304 kgf·m", extra: "230.42 kgf·cm", extra2: "22.60 N·m" },
      { fromVal: "250 lb·in", toVal: "2.880 kgf·m", extra: "288.03 kgf·cm", extra2: "28.25 N·m" }
    ]
  },
  applications: {
    title: "Practical Industrial & Trade Uses",
    items: [
      {
        title: "Japanese Motorcycle & Powersports Maintenance",
        text: "Technical service manuals from vintage Honda, Yamaha, Suzuki, and Kawasaki motorcycles historically listed fastener torque ratings in kgf·m or kgf·cm. Technicians in the US convert these numbers into pound-inches for standard shop torque drivers."
      },
      {
        title: "Imported Machine Tool Maintenance",
        text: "Milling machines, CNC lathes, and press dies imported from Japan, South Korea, and Taiwan frequently carry plate labels and maintenance guides in kgf·m. Maintaining correct clamping forces on delicate guide rails requires accurate conversion from inch-pounds."
      },
      {
        title: "Marine Outboard Motor Servicing",
        text: "Small marine outboards manufactured overseas utilize aluminum castings and stainless steel M5/M6 fasteners specified in kilogram-force meters, requiring conversion to inch-pounds during carburetor and water pump overhauls."
      },
      {
        title: "Commercial Agricultural Machinery",
        text: "Older diesel tractors and harvesting implements built under metric gravitational standards retain kgf·m fastener schedules on hydraulic control valves and fuel injection pumps."
      }
    ]
  },
  pitfalls: {
    title: "Common Mistakes When Converting lb·in to kgf·m",
    items: [
      "Confusing kgf·m with kgf·cm: 1 kgf·m equals 100 kgf·cm. A specification of 100 kgf·cm is only 1 kgf·m (86.8 lb·in). Misreading cm as m will lead to catastrophic fastener failure.",
      "Rounding the 0.01152 factor too early: Because kgf·m values for small fasteners are small decimals (typically 0.2 to 2.0 kgf·m), rounding 0.01152 to 0.01 creates an unacceptably high 15% error.",
      "Conflating kgf·m with N·m: 1 kgf·m is roughly 9.81 times larger than 1 N·m. Always verify which metric torque unit is specified on the blueprint.",
      "Using an uncalibrated low-torque wrench: Small fractional kgf·m torque settings require calibrated 1/4-inch drive torque tools to prevent stripping soft aluminum threads."
    ]
  },
  faqs: [
    {
      question: "How do I convert pound-inches to kilogram-force meters?",
      answer: "Multiply the pound-inch value by 0.01152125 (or divide by 86.7962). For example, 100 lb·in × 0.01152125 = 1.152 kgf·m."
    },
    {
      question: "How many pound-inches are in 1 kilogram-force meter?",
      answer: "There are approximately 86.7962 pound-inches in 1 kilogram-force meter (kgf·m)."
    },
    {
      question: "What is the difference between kgf·m and kgf·cm?",
      answer: "1 kilogram-force meter (kgf·m) equals 100 kilogram-force centimeters (kgf·cm). 1 pound-inch equals 0.01152 kgf·m or 1.152 kgf·cm."
    },
    {
      question: "Is kgf·m an official SI unit?",
      answer: "No. The kilogram-force meter is a legacy gravitational metric unit. The official SI unit of torque is the Newton-meter (N·m), where 1 kgf·m = 9.80665 N·m."
    },
    {
      question: "What is 50 lb·in in kgf·m?",
      answer: "50 lb·in equals approximately 0.576 kgf·m (50 × 0.01152125 = 0.5761 kgf·m), or about 57.6 kgf·cm."
    },
    {
      question: "Why do Japanese motorcycle manuals use kgf·m?",
      answer: "Older Japanese Industrial Standards (JIS) relied on the gravitational metric system (kilogram-force). While modern manuals use N·m, millions of vintage bikes and machine manuals still feature kgf·m and kgf·cm."
    },
    {
      question: "How do I convert 1.5 kgf·m to inch-pounds?",
      answer: "Multiply 1.5 by 86.7962: 1.5 × 86.7962 = 130.19 lb·in (about 130 in-lb)."
    },
    {
      question: "What is the formula for converting kgf·m to lb·in?",
      answer: "The formula is: lb·in = kgf·m × 86.79617."
    }
  ],
  relatedList: [
    { label: "Kilogram-Force Meter to Pound-Inch", from: "kilogram-force-meter", to: "pound-inch" },
    { label: "Pound-Inch to Newton-Meter", from: "pound-inch", to: "newton-meter" },
    { label: "Pound-Inch to Pound-Foot", from: "pound-inch", to: "pound-foot" },
    { label: "Kilogram-Force Meter to Newton-Meter", from: "kilogram-force-meter", to: "newton-meter" }
  ],
  relatedArticles: [
    {
      title: "Kilogram-Force Meter to Pound-Inch Conversion Guide",
      description: "Convert Japanese and European gravitational metric torque specifications into inch-pounds.",
      from: "kilogram-force-meter",
      to: "pound-inch"
    },
    {
      title: "Pound-Inch to Newton-Meter Conversion Guide",
      description: "Master the conversion from imperial inch-pounds to standard modern SI Newton-meters.",
      from: "pound-inch",
      to: "newton-meter"
    }
  ],
  references: [
    "JIS B 0101: Screw Threads and Fasteners — Vocabulary and Torque Standards",
    "ISO 80000-4: Quantities and units — Part 4: Mechanics",
    "NIST Guide for the Use of the International System of Units (SI)",
    "ASME B107.300: Torque Instruments and Calibration Procedures"
  ]
};
