import { CustomArticleData } from "./types";

export const poundFootToPoundInch: CustomArticleData = {
  fromUnitId: "pound-foot",
  toUnitId: "pound-inch",
  seoTitle: "Pound-Foot to Pound-Inch Converter (lb·ft to lb·in)",
  metaDescription: "Convert pound-feet to pound-inches (lb·ft to lb·in / ft-lb to in-lb) instantly. Exact 12x factor, formula, torque wrench conversions, tables, and FAQs.",
  h1: "Pound-Foot to Pound-Inch Converter",
  introduction: [
    "The pound-foot (lb·ft, commonly called foot-pound) and the pound-inch (lb·in, commonly called inch-pound) are the two primary torque units used in the United States Customary and British Imperial systems of measurement. Both units describe the moment of rotational force, with the sole difference being the length of the moment arm: one foot versus one inch.",
    "Converting pound-feet to pound-inches is one of the most critical calculations in automotive, aerospace, and precision mechanics. Because there are exactly 12 inches in one foot, applying one pound of force at a distance of one foot generates exactly 12 times the rotational moment of applying that same one pound of force at a distance of one inch. Therefore, 1 pound-foot equals exactly 12 pound-inches (1 lb·ft = 12 lb·in).",
    "This comprehensive reference guide details the mathematical relationship, highlights critical safety protocols for torque wrench selection, provides worked examples for delicate engine and chassis fasteners, and includes a complete conversion chart."
  ],
  quickAnswer: {
    text: "To convert pound-feet to pound-inches, multiply the value by 12. For example, a spark plug torque specification of 15 lb·ft equals exactly 180 lb·in (inch-pounds).",
    formulaDisplay: "\\text{lb·in} = \\text{lb·ft} \\times 12",
    subtext: "1 pound-foot equals exactly 12 pound-inches (in-lb)."
  },
  aboutSourceUnit: {
    title: "Understanding the Pound-Foot (lb·ft)",
    text: "The pound-foot (symbol: lb·ft or lbf·ft) is the imperial unit used for medium to heavy torque applications. Defined as the turning effort generated by one pound-force exerted at a radial distance of one foot (1 lb·ft = 1 lbf × 1 ft), it is standard for engine crankshafts, suspension components, transmission bell housings, and wheel lug nuts."
  },
  aboutTargetUnit: {
    title: "Understanding the Pound-Inch (lb·in)",
    text: "The pound-inch (symbol: lb·in or in-lb) is the imperial unit used for low-torque, high-precision assemblies. Representing one pound-force acting at a one-inch radius (1 lb·in = 1 lbf × 1 in = 1/12 lb·ft), it is used on precision torque screwdrivers and 1/4-inch drive torque wrenches for valve covers, oil pan flanges, optical sights, and electrical terminal lugs."
  },
  relationship: "Because the international foot is defined as exactly 12 inches (1 ft = 12 in), the torque relationship is exact and contains zero rounding error: 1 lb·ft = 12 lb·in. Conversely, 1 lb·in = 1/12 lb·ft ≈ 0.0833333 lb·ft.",
  relationshipTitle: "Imperial Torque Lever Arm Comparison",
  relationshipItems: [
    { label: "1.0 lb·ft", value: "12 lb·in (1 lbf at 12 inches vs 1 inch radius)" },
    { label: "5.0 lb·ft", value: "60 lb·in (Valve cover perimeter bolts)" },
    { label: "10 lb·ft", value: "120 lb·in (Thermostat housing & water pump bolts)" },
    { label: "15 lb·ft", value: "180 lb·in (Automotive spark plugs in aluminum heads)" },
    { label: "20 lb·ft", value: "240 lb·in (Oil pan drain plug & transmission pan bolts)" }
  ],
  formula: {
    text: "Multiply the torque in pound-feet by 12 to calculate the equivalent torque in pound-inches.",
    math: "\\tau_{(\\text{lb·in})} = \\tau_{(\\text{lb·ft})} \\times 12",
    subtext: "To convert pound-inches back to pound-feet, divide by 12 (multiply by 0.083333)."
  },
  formulaTitle: "lb·ft to lb·in Exact Formula",
  practicalTip: {
    title: "Mental Multiplication Rule",
    text: "To multiply by 12 in your head quickly: multiply by 10, then add twice the original number (e.g., 14 lb·ft × 12 → 140 + 28 = 168 lb·in)."
  },
  expertNote: {
    title: "Torque Wrench Drive Size & Calibration Safety",
    text: "Never use a large 1/2-inch drive torque wrench to tighten a bolt specified in inch-pounds. Lower-range fasteners below 20 lb·ft (240 lb·in) should always be tightened using a dedicated 1/4-inch or 3/8-inch drive inch-pound torque wrench to ensure sensitivity and avoid fastener snapping."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Automotive Spark Plug Installation",
        subtitle: "A service manual specifies 14 lb·ft for spark plugs. Convert to lb·in for an inch-pound torque wrench.",
        steps: [
          "Record initial value: 14 lb·ft.",
          "Multiply by 12: lb·in = 14 × 12.",
          "Calculate: 14 × 12 = 168.",
          "Final Result: 14 lb·ft equals exactly 168 lb·in."
        ]
      },
      {
        title: "Example 2: Transmission Pan Gasket Bolts",
        subtitle: "An automatic transmission filter kit specifies 8.5 lb·ft on perimeter bolts. Convert to in-lb.",
        steps: [
          "Starting value: 8.5 lb·ft.",
          "Multiply by 12: 8.5 × 12 = 102.",
          "Final Result: 8.5 lb·ft equals exactly 102 lb·in (set tool to 102 in-lb)."
        ]
      },
      {
        title: "Example 3: Intake Manifold Flange Bolts",
        subtitle: "Convert a manufacturer spec of 18 lb·ft into pound-inches.",
        steps: [
          "Starting value: 18 lb·ft.",
          "Multiply by 12: 18 × 12 = 216.",
          "Final Result: 18 lb·ft equals 216 lb·in."
        ]
      }
    ]
  },
  table: {
    title: "Pound-Foot to Pound-Inch Conversion Table",
    headers: ["Pound-Feet (lb·ft / ft-lb)", "Pound-Inches (lb·in / in-lb)", "Common Automotive & Mechanical Context"],
    rows: [
      { fromVal: "1 lb·ft", toVal: "12 lb·in", extra: "Delicate plastic sensor bracket screws" },
      { fromVal: "2 lb·ft", toVal: "24 lb·in", extra: "Carburetor top cover & throttle body sensors" },
      { fromVal: "3 lb·ft", toVal: "36 lb·in", extra: "Bicycle disc brake rotor mounting bolts" },
      { fromVal: "4 lb·ft", toVal: "48 lb·in", extra: "Small electronics ground terminals" },
      { fromVal: "5 lb·ft", toVal: "60 lb·in", extra: "Valve cover perimeter bolts & plastic clips" },
      { fromVal: "7.5 lb·ft", toVal: "90 lb·in", extra: "Automatic transmission valve body bolts" },
      { fromVal: "10 lb·ft", toVal: "120 lb·in", extra: "Engine water pump M6 perimeter flange bolts" },
      { fromVal: "12 lb·ft", toVal: "144 lb·in", extra: "Thermostat housing & timing cover bolts" },
      { fromVal: "15 lb·ft", toVal: "180 lb·in", extra: "Spark plugs in aluminum cylinder heads" },
      { fromVal: "18 lb·ft", toVal: "216 lb·in", extra: "Intake manifold bolts & oil filter housing" },
      { fromVal: "20 lb·ft", toVal: "240 lb·in", extra: "Oil pan drain plug on aluminum sump" },
      { fromVal: "25 lb·ft", toVal: "300 lb·in", extra: "Brake caliper slider pin bolts (3/8-inch drive range)" }
    ]
  },
  applications: {
    title: "Key Automotive & Mechanical Uses",
    items: [
      {
        title: "Automotive Engine Gasket & Pan Sealing",
        text: "Gasket materials on stamped steel or composite oil pans, transmission pans, and valve covers require uniform tightening in inch-pounds to prevent pinch distortion and fluid leaks."
      },
      {
        title: "Small Engine & Motorcycle Repair",
        text: "Motorcycle cylinder bases, crankcases, and carburetor flanges utilize M5 and M6 hardware where torque specs in foot-pounds must be converted to inch-pounds for 1/4-inch drive click tools."
      },
      {
        title: "Aerospace Structural & Avionics Assembly",
        text: "Airframe brackets and avionics boxes are mounted with AN/MS hardware whose engineering drawings specify torque in inch-pounds to avoid thread deformation."
      },
      {
        title: "HVAC & Electrical Switchgear",
        text: "National Electrical Code (NEC 110.14) mandates calibrated torque on circuit breaker terminal screws, often listed in lb·in to prevent high-resistance thermal hotspots."
      }
    ]
  },
  pitfalls: {
    title: "Critical Torque Tooling Pitfalls",
    items: [
      "Confusing Units in Reverse: Setting 120 lb·ft on a bolt that required 120 lb·in applies 10 times the breaking strength of an M6 bolt, snapping it instantly.",
      "Using the Low End of a 1/2-Inch Wrench: Using a 10–150 lb·ft wrench set at 10 lb·ft has high percentage error (±20% or worse). Use an inch-pound wrench set to 120 lb·in instead (±4% accuracy).",
      "Omitting Conversion When Reading Manuals: Older manuals often switch between ft-lbs and in-lbs on the same page. Always check the unit column in service specification tables.",
      "Neglecting Spring Relaxation After Use: Always return mechanical spring-type click wrenches to their lowest scale setting after use to avoid calibration drift."
    ]
  },
  faqs: [
    {
      question: "How do I convert pound-feet to pound-inches?",
      answer: "Multiply the pound-foot (lb·ft) value by 12. For example, 15 lb·ft × 12 = 180 lb·in."
    },
    {
      question: "How many inch-pounds are in 1 foot-pound?",
      answer: "There are exactly 12 inch-pounds in 1 foot-pound (1 lb·ft = 12 lb·in)."
    },
    {
      question: "What is 10 lb·ft in inch-pounds?",
      answer: "10 lb·ft equals exactly 120 lb·in (10 × 12 = 120)."
    },
    {
      question: "What is 20 ft-lb in in-lb?",
      answer: "20 ft-lb equals exactly 240 in-lb (20 × 12 = 240)."
    },
    {
      question: "How do I convert inch-pounds back to foot-pounds?",
      answer: "Divide the inch-pound value by 12. For example, 96 in-lb ÷ 12 = 8 ft-lb."
    },
    {
      question: "Why should I use an inch-pound torque wrench instead of a foot-pound wrench?",
      answer: "Low torque values (under 15–20 lb·ft) sit at the inaccurate bottom edge of foot-pound torque wrenches. An inch-pound torque wrench operates in the middle of its calibrated range, ensuring precise clamping force without snapping small bolts."
    },
    {
      question: "What is 7.5 lb·ft in lb·in?",
      answer: "7.5 lb·ft equals exactly 90 lb·in (7.5 × 12 = 90)."
    },
    {
      question: "Is ft-lb the same as in-lb?",
      answer: "No. 1 ft-lb is twelve times larger than 1 in-lb. Applying 50 ft-lb when 50 in-lb was intended will apply 600 in-lb of torque, destroying the fastener."
    }
  ],
  relatedList: [
    { label: "Pound-Inch to Pound-Foot", from: "pound-inch", to: "pound-foot" },
    { label: "Pound-Foot to Newton-Meter", from: "pound-foot", to: "newton-meter" },
    { label: "Newton-Meter to Pound-Inch", from: "newton-meter", to: "pound-inch" },
    { label: "Pound-Foot to Newton-Centimeter", from: "pound-foot", to: "newton-centimeter" }
  ],
  relatedArticles: [
    {
      title: "Pound-Foot to Newton-Meter Conversion Guide",
      description: "Convert imperial foot-pounds into SI Newton-meters for international automotive specifications.",
      from: "pound-foot",
      to: "newton-meter"
    },
    {
      title: "Newton-Meter to Pound-Inch Conversion Guide",
      description: "Convert metric torque into precision inch-pounds for electronics, bicycles, and firearms.",
      from: "newton-meter",
      to: "pound-inch"
    }
  ],
  references: [
    "ASME B107.300: Manual Torque Tools — Precision & Calibration Standards",
    "SAE J1701: Torque-Tension Relationship for Threaded Fasteners",
    "National Electrical Code (NEC 110.14): Electrical Connections and Fastener Torque",
    "FAA Aviation Maintenance Technician Handbook — General (FAA-H-8083-30A)"
  ]
};
