import { CustomArticleData } from "./types";

export const soundPressureToDecibelSpl: CustomArticleData = {
  fromUnitId: "sound-pressure",
  toUnitId: "decibel-spl",
  seoTitle: "Sound Pressure to Decibel SPL Converter | Pa to dB SPL",
  metaDescription: "Convert Sound Pressure to Decibel Sound Pressure Level (Pa to dB SPL). Master the logarithmic formula, reference threshold of 20 µPa, worked examples, and acoustic tables.",
  canonicalUrl: "https://unitsconvertors.com/sound-pressure-to-decibel-spl",
  h1: "Sound Pressure to Decibel SPL Converter",
  introduction: [
    "Sound pressure represents the instantaneous or root-mean-square (RMS) atmospheric pressure fluctuation generated by an acoustic wave, measured linearly in pascals (Pa or N/m²). Because human auditory sensitivity encompasses a linear pressure range exceeding 10,000,000 to 1, acoustic engineering universally expresses airborne acoustic levels using Decibel Sound Pressure Level (dB SPL).",
    "Decibel Sound Pressure Level translates physical force per unit area into a manageable logarithmic scale anchored to 20 micropascals (p₀ = 0.00002 Pa in air). This reference baseline represents the minimum acoustic pressure required to stimulate the human auditory system at 1,000 Hz, defining 0 dB SPL.",
    "Converting sound pressure in pascals to dB SPL is a cornerstone calculation in sound level metering, studio acoustics, industrial noise assessment, and hearing conservation. This reference provides the theoretical derivation, formulas, step-by-step examples, and comprehensive conversion tables."
  ],
  quickAnswer: {
    text: "To convert Sound Pressure in pascals to Decibel SPL, divide the sound pressure by 0.00002 Pa, compute the base-10 logarithm, and multiply by 20: dB SPL = 20 × log₁₀(p / 0.00002). For example, a sound pressure of 1.0 Pascal equals approximately 93.98 dB SPL (standardized as 94 dB SPL).",
    formulaDisplay: "dB SPL = 20 × log₁₀(p / 0.00002)",
    subtext: "Where p is RMS sound pressure in pascals and 0.00002 Pa (20 µPa) is the standardized reference pressure in air."
  },
  aboutSourceUnit: {
    title: "Understanding Sound Pressure (p)",
    text: "Sound Pressure (symbol: p) is the dynamic, alternating pressure perturbation around the static barometric atmospheric pressure (approximately 101,325 Pa at sea level), measured in pascals (Pa = 1 N/m²). In acoustics, sound pressure is measured using sensitive condenser or piezoelectric microphones and is almost always evaluated as a root-mean-square (RMS) amplitude."
  },
  aboutTargetUnit: {
    title: "Understanding Decibel Sound Pressure Level (dB SPL)",
    text: "Decibel Sound Pressure Level (symbol: dB SPL) is a logarithmic ratio expressing acoustic field magnitude relative to the international reference threshold of 20 micropascals (20 µPa) in air. Because sound pressure is a root-power or field quantity, the ratio uses a multiplier of 20. On this scale, 0 dB SPL is the threshold of hearing, 94 dB SPL is the standard microphone test tone (1 Pa), and 120 dB SPL marks the threshold of physical discomfort."
  },
  relationship: "Sound pressure p (in pascals) and sound pressure level L_p (in dB SPL) are governed by L_p = 20 log₁₀(p / p₀), where reference pressure p₀ = 0.00002 Pa. Every tenfold increase in sound pressure adds exactly 20 dB SPL to the measured level, while doubling sound pressure increases the level by approximately 6.02 dB SPL.",
  relationshipTitle: "Sound Pressure to Decibel SPL Scale Benchmarks",
  relationshipItems: [
    { label: "0.00002 Pa (20 µPa)", value: "0.00 dB SPL (Nominal human hearing threshold)" },
    { label: "0.0002 Pa (200 µPa)", value: "20.00 dB SPL (Whisper, recording studio background)" },
    { label: "0.002 Pa (2 mPa)", value: "40.00 dB SPL (Quiet residential room, library)" },
    { label: "0.02 Pa (20 mPa)", value: "60.00 dB SPL (Normal conversational speech at 1 meter)" },
    { label: "0.2 Pa (200 mPa)", value: "80.00 dB SPL (Curbside urban traffic, vacuum cleaner)" },
    { label: "1.0 Pa (1,000 mPa)", value: "93.98 dB SPL (~94 dB SPL calibration tone)" },
    { label: "2.0 Pa", value: "100.00 dB SPL (Pneumatic drill at 3 meters)" },
    { label: "20.0 Pa", value: "120.00 dB SPL (Human threshold of acoustic discomfort)" },
    { label: "200.0 Pa", value: "140.00 dB SPL (Jet aircraft takeoff at 30 meters)" }
  ],
  formula: {
    text: "Divide the RMS sound pressure in pascals by the reference pressure of 0.00002 Pa, compute the common logarithm (base 10), and multiply the result by 20.",
    math: "dB SPL = 20 × log₁₀(p / 0.00002 Pa)",
    subtext: "For airborne sound according to ANSI S1.1 and ISO 1683 standards."
  },
  formulaTitle: "Formula: Sound Pressure to Decibel SPL",
  practicalTip: {
    title: "The 6 dB Doubling Rule",
    text: "In acoustic pressure measurement, doubling the physical pressure in pascals (a 2× factor) increases the sound pressure level by approximately 6.02 dB SPL. Conversely, halving the pressure reduces the level by 6.02 dB SPL."
  },
  expertNote: {
    title: "IEC 61672 Class 1 Sound Level Meter Calibration",
    text: "Precision sound level meters are calibrated before every field measurement using an acoustic pistonphone or sound calibrator that emits a 1,000 Hz sinusoidal wave at an exact RMS pressure of 1.0 Pascal (94.0 dB SPL) into the microphone cavity."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Acoustic Calibrator Signal (1.0 Pa)",
        subtitle: "Calculate the dB SPL value for a standard 1.0 Pascal calibration tone.",
        steps: [
          "State the acoustic pressure: p = 1.0 Pa.",
          "Identify the reference pressure: p₀ = 0.00002 Pa.",
          "Form the pressure ratio: 1.0 / 0.00002 = 50,000.",
          "Compute the base-10 logarithm: log₁₀(50,000) ≈ 4.69897.",
          "Multiply by 20: 20 × 4.69897 = 93.9794 dB SPL.",
          "Final Result: 1.0 Pascal equals approximately 93.98 dB SPL (standardized as 94 dB SPL)."
        ]
      },
      {
        title: "Example 2: Conversational Speech (0.02 Pa)",
        subtitle: "Convert the acoustic pressure of normal speech into sound pressure level.",
        steps: [
          "State the acoustic pressure: p = 0.02 Pa.",
          "Form the pressure ratio: 0.02 / 0.00002 = 1,000.",
          "Compute log₁₀(1,000) = 3.0.",
          "Multiply by 20: 20 × 3.0 = 60.0 dB SPL.",
          "Final Result: 0.02 Pascals equals exactly 60 dB SPL."
        ]
      },
      {
        title: "Example 3: Industrial Machinery Noise (2.0 Pa)",
        subtitle: "Find the dB SPL level for heavy machinery generating 2.0 Pascals of sound pressure.",
        steps: [
          "State the acoustic pressure: p = 2.0 Pa.",
          "Form the pressure ratio: 2.0 / 0.00002 = 100,000.",
          "Compute log₁₀(100,000) = 5.0.",
          "Multiply by 20: 20 × 5.0 = 100.0 dB SPL.",
          "Final Result: 2.0 Pascals equals exactly 100 dB SPL."
        ]
      }
    ]
  },
  table: {
    title: "Sound Pressure (Pa) to Decibel SPL Reference Table",
    headers: ["Sound Pressure (Pa)", "Sound Pressure Level (dB SPL)", "Typical Environmental Context"],
    rows: [
      { fromVal: "0.00002 Pa", toVal: "0.00 dB SPL", extra: "Human hearing threshold at 1 kHz" },
      { fromVal: "0.000063 Pa", toVal: "10.00 dB SPL", extra: "Calm breathing, quiet recording booth" },
      { fromVal: "0.0002 Pa", toVal: "20.00 dB SPL", extra: "Whisper at 1 meter, leaves rustling" },
      { fromVal: "0.000632 Pa", toVal: "30.00 dB SPL", extra: "Quiet suburban bedroom at midnight" },
      { fromVal: "0.002 Pa", toVal: "40.00 dB SPL", extra: "Quiet library study room" },
      { fromVal: "0.006325 Pa", toVal: "50.00 dB SPL", extra: "Moderate rainfall, quiet commercial office" },
      { fromVal: "0.02 Pa", toVal: "60.00 dB SPL", extra: "Normal spoken conversation at 1 meter" },
      { fromVal: "0.06325 Pa", toVal: "70.00 dB SPL", extra: "Busy restaurant, passenger car interior" },
      { fromVal: "0.2 Pa", toVal: "80.00 dB SPL", extra: "Curbside city traffic, noisy food blender" },
      { fromVal: "0.3557 Pa", toVal: "85.00 dB SPL", extra: "OSHA 8-hour occupational action limit" },
      { fromVal: "0.6325 Pa", toVal: "90.00 dB SPL", extra: "Heavy diesel truck pass-by at 10 meters" },
      { fromVal: "1.0 Pa", toVal: "93.98 dB SPL", extra: "Standard 94 dB microphone calibrator tone" },
      { fromVal: "2.0 Pa", toVal: "100.00 dB SPL", extra: "Pneumatic jackhammer at 3 meters" },
      { fromVal: "6.325 Pa", toVal: "110.00 dB SPL", extra: "Live rock concert, car horn at 1 meter" },
      { fromVal: "10.0 Pa", toVal: "113.98 dB SPL", extra: "Secondary 114 dB calibrator reference" },
      { fromVal: "20.0 Pa", toVal: "120.00 dB SPL", extra: "Human threshold of acoustic pain" },
      { fromVal: "63.25 Pa", toVal: "130.00 dB SPL", extra: "Pneumatic riveting hammer at operator ear" },
      { fromVal: "200.0 Pa", toVal: "140.00 dB SPL", extra: "Jet aircraft takeoff at 30 meters" }
    ]
  },
  applications: {
    title: "Acoustic Engineering & Environmental Applications",
    items: [
      {
        title: "Environmental Noise Impact Studies",
        text: "Converting continuous pressure data from remote monitoring stations into hourly L_eq dB SPL ratings for regulatory noise zoning."
      },
      {
        title: "Occupational Noise Dosimetry",
        text: "Assessing factory worker noise exposure to comply with OSHA 90 dBA permissible exposure limits and 85 dBA action levels."
      },
      {
        title: "Concert Venue & Public Address Design",
        text: "Modeling direct and reverberant sound pressure fields across auditorium seating planes to ensure intelligible speech transmission."
      }
    ]
  },
  pitfalls: {
    title: "Common Pitfalls & Mistakes",
    items: [
      "Using 10 log₁₀ instead of 20 log₁₀: Acoustic pressure is a field amplitude quantity, requiring a factor of 20, whereas acoustic power uses 10.",
      "Applying underwater acoustic standards: Marine acoustics uses a reference pressure of 1 µPa, which yields an answer 26 dB higher than the airborne 20 µPa standard.",
      "Confusing acoustic fluctuations with barometric pressure: Atmospheric air pressure is roughly 101,325 Pa, whereas acoustic waves represent minute dynamic fluctuations of 0.00002 to 20 Pa.",
      "Attempting to calculate the logarithm of zero: True silence (0 Pa) mathematically corresponds to negative infinity dB SPL; the practical reference baseline is 20 µPa."
    ]
  },
  faqs: [
    {
      question: "How many dB SPL is 1 Pascal of sound pressure?",
      answer: "1 Pascal of RMS sound pressure equals approximately 93.98 dB SPL. In commercial test instruments and calibration equipment, this is conventionally rounded and standardized as 94 dB SPL."
    },
    {
      question: "What is the reference pressure for dB SPL in air?",
      answer: "The international reference pressure for airborne sound is 20 micropascals (20 µPa, equal to 0.00002 Pa or 2 × 10⁻⁵ N/m²). This value represents the average human threshold of audibility at 1 kHz."
    },
    {
      question: "Why does the dB SPL formula multiply by 20 rather than 10?",
      answer: "Acoustic energy and power are proportional to the square of acoustic pressure (P ∝ p²). Expressing the power ratio logarithmically gives 10 × log₁₀(p² / p₀²), which simplifies by logarithmic rules to 20 × log₁₀(p / p₀)."
    },
    {
      question: "What sound pressure in pascals corresponds to 0 dB SPL?",
      answer: "A sound pressure of exactly 0.00002 Pascals (20 µPa) produces 0 dB SPL, representing the nominal baseline of human hearing."
    },
    {
      question: "Can dB SPL be a negative number?",
      answer: "Yes. Any sound pressure lower than the 20 µPa reference baseline produces a negative dB SPL value. For example, 0.000002 Pa (2 µPa) equals -20 dB SPL."
    },
    {
      question: "What sound pressure corresponds to normal conversation?",
      answer: "Normal conversational speech at a distance of 1 meter typically produces approximately 60 dB SPL, which equals an acoustic pressure of 0.02 Pascals (20 mPa)."
    },
    {
      question: "What pressure corresponds to the threshold of pain?",
      answer: "The human auditory threshold of pain begins around 120 dB SPL to 130 dB SPL, which corresponds to an RMS pressure of 20 to 63.2 Pascals."
    },
    {
      question: "How does a 6 dB SPL increase affect sound pressure in pascals?",
      answer: "An increase of approximately 6.02 dB SPL corresponds to an exact doubling of the sound pressure in pascals (a 2:1 linear pressure ratio)."
    }
  ],
  references: [
    "ISO 80000-8: Quantities and units — Part 8: Acoustics",
    "IEC 61672-1: Electroacoustics — Sound level meters — Part 1: Specifications",
    "ANSI/ASA S1.1: Acoustical Terminology Standards",
    "NIST Special Publication 811: Guide for the Use of the International System of Units"
  ]
};
