import { CustomArticleData } from "./types";

export const wattToGigawatt: CustomArticleData = {
  fromUnitId: "watt",
  toUnitId: "gigawatt",
  seoTitle: "Watt to Gigawatt Converter (W to GW)",
  metaDescription: "Convert Watts to Gigawatts (W to GW) accurately. Learn the 1,000,000,000 conversion factor, macro-grid scale energy calculations, formulas, and FAQs.",
  h1: "Watt to Gigawatt Converter",
  introduction: [
    "The Watt (W) and Gigawatt (GW) are metric power units representing opposite ends of the energy scale. While a Watt quantifies small-scale energy consumption—such as an LED light or computer processor—a Gigawatt measures immense macro-scale power capacities, including national electrical grids, nuclear power stations, massive hydroelectric dams, and continental energy infrastructure.",
    "Converting Watts to Gigawatts relies on the International System of Units (SI) prefix giga, which signifies a multiplier of one billion (10⁹). Because one Gigawatt equals exactly 1,000,000,000 Watts, converting Watts to Gigawatts requires dividing the power in Watts by 1,000,000,000.",
    "This guide explains the mathematical conversion formula, provides step-by-step macro-engineering calculation examples, offers structured conversion tables, and explores real-world utility grid applications."
  ],
  quickAnswer: {
    text: "To convert Watts to Gigawatts, divide the power value in Watts by 1,000,000,000. For example, a 1,200,000,000 W nuclear reactor output equals 1.2 GW.",
    formulaDisplay: "GW = W ÷ 1,000,000,000",
    subtext: "1 Watt is equal to 0.000000001 Gigawatts (1 × 10⁻⁹ GW)."
  },
  aboutSourceUnit: {
    title: "Understanding the Watt (W)",
    text: "The Watt (symbol: W) is the fundamental SI unit of power, equivalent to one Joule per second (1 J/s). It serves as the baseline measurement for electrical, mechanical, and thermal energy flow rates worldwide."
  },
  aboutTargetUnit: {
    title: "Understanding the Gigawatt (GW)",
    text: "The Gigawatt (symbol: GW) is an SI multiple unit equal to 1,000,000,000 Watts (10⁹ W), 1,000 Megawatts (MW), or 1,000,000 Kilowatts (kW). It is the standard metric used in energy policy, national grid planning, and major power station engineering."
  },
  relationship: "The metric relationship between watts and gigawatts is defined by the SI prefix giga: 1 GW = 1,000,000,000 W = 10⁹ W. Conversely, 1 W = 0.000000001 GW = 10⁻⁹ GW.",
  relationshipTitle: "Watt vs Gigawatt Capacity Comparison",
  relationshipItems: [
    { label: "1 W", value: "0.000000001 GW (Single Watt baseline)" },
    { label: "1,000,000 W", value: "0.001 GW (1 Megawatt / 1,000 kW)" },
    { label: "100,000,000 W", value: "0.1 GW (100 Megawatt utility power plant)" },
    { label: "1,000,000,000 W", value: "1.0 GW (1,000 Megawatts / Large nuclear reactor unit)" },
    { label: "22,500,000,000 W", value: "22.5 GW (Three Gorges Dam total installed capacity)" }
  ],
  formula: {
    text: "Divide the electrical power in Watts by 1,000,000,000 to compute the power in Gigawatts.",
    math: "GW = W / 1000000000",
    subtext: "To convert Gigawatts back to Watts, multiply the Gigawatt value by 1,000,000,000."
  },
  formulaTitle: "Watt to Gigawatt Conversion Formula",
  practicalTip: {
    title: "Decimal Shift Shortcut",
    text: "To convert Watts to Gigawatts mentally, move the decimal point nine places to the left. For example, 3,500,000,000 W becomes 3.5 GW."
  },
  expertNote: {
    title: "National Grid Scale Context",
    text: "1 Gigawatt of continuous power generation is sufficient to supply roughly 750,000 average homes or power major metropolitan areas continuously."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Nuclear Power Plant Rating",
        subtitle: "Convert a 2,400,000,000 Watt nuclear facility capacity into Gigawatts.",
        steps: [
          "Identify power in Watts: 2,400,000,000 W.",
          "Apply formula: GW = 2,400,000,000 ÷ 1,000,000,000.",
          "Calculate: 2,400,000,000 ÷ 1,000,000,000 = 2.4.",
          "Result: 2,400,000,000 Watts equals 2.4 Gigawatts."
        ]
      },
      {
        title: "Example 2: Regional Offshore Wind Energy Complex",
        subtitle: "Convert 1,500,000,000 Watts generated by an offshore wind farm to Gigawatts.",
        steps: [
          "Identify power: 1,500,000,000 W.",
          "Divide by 1,000,000,000: 1,500,000,000 ÷ 1,000,000,000 = 1.5.",
          "Result: 1,500,000,000 Watts equals 1.5 GW."
        ]
      },
      {
        title: "Example 3: National Peak Grid Demand",
        subtitle: "Convert 45,000,000,000 Watts of peak electrical demand to Gigawatts.",
        steps: [
          "Identify power: 45,000,000,000 W.",
          "Divide by 1,000,000,000: 45,000,000,000 ÷ 1,000,000,000 = 45.",
          "Result: 45,000,000,000 Watts equals 45 GW."
        ]
      }
    ]
  },
  table: {
    title: "Watt to Gigawatt Conversion Table",
    headers: ["Watts (W)", "Gigawatts (GW)", "Real-World Macro Power Equivalent"],
    rows: [
      { fromVal: "1 W", toVal: "0.000000001 GW", extra: "Baseline single watt" },
      { fromVal: "10,000,000 W", toVal: "0.01 GW", extra: "10 MW industrial generation plant" },
      { fromVal: "100,000,000 W", toVal: "0.1 GW", extra: "100 MW utility solar farm" },
      { fromVal: "500,000,000 W", toVal: "0.5 GW", extra: "500 MW combined-cycle gas turbine" },
      { fromVal: "1,000,000,000 W", toVal: "1.0 GW", extra: "1,000 MW nuclear power unit" },
      { fromVal: "2,000,000,000 W", toVal: "2.0 GW", extra: "Hoover Dam hydro-electric capacity" },
      { fromVal: "5,000,000,000 W", toVal: "5.0 GW", extra: "Large regional power plant complex" },
      { fromVal: "10,000,000,000 W", toVal: "10.0 GW", extra: "Small country peak power demand" },
      { fromVal: "22,500,000,000 W", toVal: "22.5 GW", extra: "Three Gorges Dam max capacity" },
      { fromVal: "50,000,000,000 W", toVal: "50.0 GW", extra: "UK national peak electrical grid load" }
    ]
  },
  applications: {
    title: "Applications of W to GW Conversion",
    items: [
      {
        title: "National Energy Strategy & Policy",
        text: "Governments and energy commissions plan long-term decarbonization targets by aggregating gigawatt requirements for grid expansion and renewable adoption."
      },
      {
        title: "Macro Utility Power Generation",
        text: "Nuclear reactors, coal facilities, and offshore wind parks report cumulative capacity in Gigawatts to inter-state power transmission organizations."
      },
      {
        title: "Continental Energy Transmission",
        text: "High-voltage direct current (HVDC) interconnectors between nations are rated in Gigawatts to facilitate international electricity trading."
      }
    ]
  },
  pitfalls: {
    title: "Common Conversion Pitfalls",
    items: [
      "Miscounting zeros in long numerical values: Always double-check that nine decimal places are shifted when converting W to GW.",
      "Confusing GW with GWh: Gigawatt (GW) measures generation rate, whereas Gigawatt-hour (GWh) measures total electrical energy produced over time.",
      "Confusing Gigawatts (10⁹ W) with Terawatts (10¹² W)."
    ]
  },
  faqs: [
    {
      question: "How many Watts are in 1 Gigawatt?",
      answer: "There are exactly 1,000,000,000 (one billion) Watts in 1 Gigawatt."
    },
    {
      question: "What is the formula to convert Watts to Gigawatts?",
      answer: "The formula is: Gigawatts = Watts ÷ 1,000,000,000."
    },
    {
      question: "How many Megawatts equal 1 Gigawatt?",
      answer: "1 Gigawatt equals 1,000 Megawatts (MW)."
    },
    {
      question: "How many Kilowatts equal 1 Gigawatt?",
      answer: "1 Gigawatt equals 1,000,000 Kilowatts (kW)."
    },
    {
      question: "How many Gigawatts is 2,500,000,000 Watts?",
      answer: "2,500,000,000 Watts equals 2.5 Gigawatts (2,500,000,000 ÷ 1,000,000,000 = 2.5 GW)."
    },
    {
      question: "What does 1 GW of power mean in practical terms?",
      answer: "1 GW represents 1 billion Joules of energy per second, sufficient to power about 750,000 homes simultaneously."
    },
    {
      question: "How do I convert Gigawatts back to Watts?",
      answer: "Multiply the Gigawatt value by 1,000,000,000 (e.g., 3 GW × 1,000,000,000 = 3,000,000,000 W)."
    },
    {
      question: "What unit comes after Gigawatt?",
      answer: "The next standard SI power multiple after Gigawatt (10⁹ W) is the Terawatt (TW, 10¹² W or 1,000 GW)."
    }
  ],
  relatedList: [
    { label: "Watt to Kilowatt", from: "watt", to: "kilowatt" },
    { label: "Watt to Megawatt", from: "watt", to: "megawatt" },
    { label: "Kilowatt to Gigawatt", from: "kilowatt", to: "gigawatt" },
    { label: "Watt to Horsepower (Mechanical)", from: "watt", to: "horsepower-mechanical" }
  ],
  references: [
    "BIPM SI Brochure (9th Edition): Metric Prefixes and Units of Power.",
    "NIST Special Publication 811: Guide for the Use of the International System of Units.",
    "International Energy Agency (IEA): Electricity Information & Grid Standards."
  ]
};
