import { CustomArticleData } from "./types";

export const wattToMegawatt: CustomArticleData = {
  fromUnitId: "watt",
  toUnitId: "megawatt",
  seoTitle: "Watt to Megawatt Converter (W to MW)",
  metaDescription: "Convert Watts to Megawatts (W to MW) accurately. Learn the 1,000,000 conversion factor, grid power formulas, practical calculation examples, and FAQs.",
  h1: "Watt to Megawatt Converter",
  introduction: [
    "The Watt (W) and Megawatt (MW) are key power units in the metric International System of Units (SI). While the Watt measures small to moderate energy transfer rates—such as lighting, computing, and small motors—the Megawatt measures large-scale utility power generation, industrial plant loads, wind turbine capacity, and regional electricity grids.",
    "Converting Watts to Megawatts bridges localized electrical measurements with macro-scale power station capacities. Driven by the SI prefix mega (meaning one million), one Megawatt equals exactly 1,000,000 Watts. Therefore, converting Watts to Megawatts requires dividing the wattage by 1,000,000.",
    "This technical guide details the conversion formula from watts to megawatts, provides step-by-step engineering calculation examples, presents structured conversion tables, and explores industrial power plant applications."
  ],
  quickAnswer: {
    text: "To convert Watts to Megawatts, divide the power rating in Watts by 1,000,000. For example, a 2,500,000 W utility wind turbine generates 2.5 MW, and 500,000 W equals 0.5 MW.",
    formulaDisplay: "MW = W ÷ 1,000,000",
    subtext: "1 Watt is equal to 0.000001 Megawatts (1 × 10⁻⁶ MW)."
  },
  aboutSourceUnit: {
    title: "Understanding the Watt (W)",
    text: "The Watt (symbol: W) is the foundational SI unit of power, equivalent to one Joule per second (1 J/s). It quantifies the rate of energy consumption or output across electrical circuits, mechanical shafts, and thermal systems."
  },
  aboutTargetUnit: {
    title: "Understanding the Megawatt (MW)",
    text: "The Megawatt (symbol: MW) is an SI multiple unit equal to 1,000,000 Watts (10⁶ W) or 1,000 Kilowatts. It serves as the primary metric for specifying electric power plant output, grid transformer capacity, utility-scale battery storage, and heavy industrial machinery."
  },
  relationship: "The relationship between watts and megawatts is defined by the SI prefix system: 1 MW = 1,000,000 W = 10⁶ W. Conversely, 1 W = 0.000001 MW = 10⁻⁶ MW.",
  relationshipTitle: "Watt vs Megawatt Capacity Scale",
  relationshipItems: [
    { label: "1 W", value: "0.000001 MW (Minimal power)" },
    { label: "1,000 W", value: "0.001 MW (1 Kilowatt load)" },
    { label: "100,000 W", value: "0.1 MW (Commercial building peak power)" },
    { label: "1,000,000 W", value: "1.0 MW (Industrial facility load / 1,000 kW)" },
    { label: "3,000,000 W", value: "3.0 MW (Modern onshore utility wind turbine)" }
  ],
  formula: {
    text: "Divide the power in Watts by 1,000,000 to express the value in Megawatts.",
    math: "MW = W / 1000000",
    subtext: "To convert Megawatts back to Watts, multiply the Megawatt value by 1,000,000."
  },
  formulaTitle: "Watt to Megawatt Conversion Formula",
  practicalTip: {
    title: "Decimal Movement Shortcut",
    text: "To convert Watts to Megawatts quickly, shift the decimal point six places to the left. For example, 5,200,000 W becomes 5.2 MW."
  },
  expertNote: {
    title: "Grid Capacity Scale",
    text: "In utility energy planning, 1 MW of generating capacity typically powers approximately 750 to 1,000 average Western homes continuously, depending on regional climate and efficiency."
  },
  examples: {
    title: "Step-by-Step Conversion Examples",
    items: [
      {
        title: "Example 1: Utility Solar Farm Power Output",
        subtitle: "Convert 15,000,000 Watts generated by a solar array to Megawatts.",
        steps: [
          "Identify power in Watts: 15,000,000 W.",
          "Apply formula: MW = 15,000,000 ÷ 1,000,000.",
          "Calculate: 15,000,000 ÷ 1,000,000 = 15.",
          "Result: 15,000,000 Watts equals 15 Megawatts."
        ]
      },
      {
        title: "Example 2: Offshore Wind Turbine Capacity",
        subtitle: "Convert an 8,000,000 Watt wind turbine rating into Megawatts.",
        steps: [
          "Identify power: 8,000,000 W.",
          "Divide by 1,000,000: 8,000,000 ÷ 1,000,000 = 8.",
          "Result: 8,000,000 Watts equals 8 MW."
        ]
      },
      {
        title: "Example 3: Data Center Power Consumption",
        subtitle: "Convert 2,400,000 Watts consumed by server racks to Megawatts.",
        steps: [
          "Identify power: 2,400,000 W.",
          "Divide by 1,000,000: 2,400,000 ÷ 1,000,000 = 2.4.",
          "Result: 2,400,000 Watts equals 2.4 MW."
        ]
      }
    ]
  },
  table: {
    title: "Watt to Megawatt Conversion Table",
    headers: ["Watts (W)", "Megawatts (MW)", "Real-World Infrastructure Equivalent"],
    rows: [
      { fromVal: "1 W", toVal: "0.000001 MW", extra: "Micro-power baseline" },
      { fromVal: "10,000 W", toVal: "0.01 MW", extra: "10 kW commercial solar roof" },
      { fromVal: "100,000 W", toVal: "0.1 MW", extra: "Small industrial workshop connection" },
      { fromVal: "500,000 W", toVal: "0.5 MW", extra: "Medium commercial building peak load" },
      { fromVal: "1,000,000 W", toVal: "1.0 MW", extra: "Standard 1 MW utility generator unit" },
      { fromVal: "2,500,000 W", toVal: "2.5 MW", extra: "Onshore wind turbine generator" },
      { fromVal: "5,000,000 W", toVal: "5.0 MW", extra: "Hyperscale data center substation module" },
      { fromVal: "10,000,000 W", toVal: "10.0 MW", extra: "Community solar project output" },
      { fromVal: "50,000,000 W", toVal: "50.0 MW", extra: "Regional hydro-electric turbine capacity" },
      { fromVal: "100,000,000 W", toVal: "100.0 MW", extra: "Utility-scale grid energy storage park" }
    ]
  },
  applications: {
    title: "Applications of W to MW Conversion",
    items: [
      {
        title: "Utility Grid Dispatch & Load Balancing",
        text: "Grid operators aggregate millions of individual household watt loads into Megawatt blocks to coordinate power station dispatch and frequency response."
      },
      {
        title: "Renewable Energy Project Planning",
        text: "Solar module output ratings in Watts are compiled into Megawatt system ratings for power purchase agreements (PPAs) and grid interconnect permits."
      },
      {
        title: "Industrial Substation Design",
        text: "Electrical engineers design high-voltage transformers by converting facility equipment wattages into Megawatts to determine primary feed sizing."
      }
    ]
  },
  pitfalls: {
    title: "Common Conversion Pitfalls",
    items: [
      "Missing zeros in division: Dividing by 100,000 instead of 1,000,000 results in a factor-of-10 error.",
      "Confusing MW with MWh: Megawatt (MW) measures instantaneous power capacity, while Megawatt-hour (MWh) measures energy produced over time.",
      "Confusing thermal megawatts (MWt) with electrical megawatts (MWe): Power plants convert thermal output to electrical output at ~33-50% efficiency."
    ]
  },
  faqs: [
    {
      question: "How many Watts are in 1 Megawatt?",
      answer: "There are exactly 1,000,000 Watts in 1 Megawatt."
    },
    {
      question: "What is the formula to convert Watts to Megawatts?",
      answer: "The formula is: Megawatts = Watts ÷ 1,000,000."
    },
    {
      question: "How many Megawatts is 5,000,000 Watts?",
      answer: "5,000,000 Watts equals 5 Megawatts (5,000,000 ÷ 1,000,000 = 5 MW)."
    },
    {
      question: "How many Kilowatts equal 1 Megawatt?",
      answer: "1 Megawatt equals 1,000 Kilowatts (kW)."
    },
    {
      question: "What does 1 MW of power mean in practical terms?",
      answer: "1 Megawatt equals 1,000,000 Joules of energy transferred per second, enough to power approximately 750 to 1,000 homes."
    },
    {
      question: "How do I convert 500 kW to Megawatts?",
      answer: "Divide 500 kW by 1,000, which equals 0.5 Megawatts."
    },
    {
      question: "What is the difference between MW and GW?",
      answer: "1 Gigawatt (GW) equals 1,000 Megawatts (MW), or 1,000,000,000 Watts."
    },
    {
      question: "Can I convert Watts directly to Megawatts using scientific notation?",
      answer: "Yes. Express the wattage value and multiply by 10⁻⁶ (e.g., 2.5 × 10⁶ W = 2.5 MW)."
    }
  ],
  relatedList: [
    { label: "Watt to Kilowatt", from: "watt", to: "kilowatt" },
    { label: "Watt to Gigawatt", from: "watt", to: "gigawatt" },
    { label: "Kilowatt to Megawatt", from: "kilowatt", to: "megawatt" },
    { label: "Watt to Horsepower (Mechanical)", from: "watt", to: "horsepower-mechanical" }
  ],
  references: [
    "BIPM SI Brochure (9th Edition): Metric Prefixes and Units of Power.",
    "NIST Special Publication 811: Guide for the Use of the International System of Units.",
    "IEEE Standard 141: Recommended Practice for Electric Power Distribution for Industrial Plants."
  ]
};
