import { updateRobotsTag, updatePageMeta } from "./seoHelpers";

/**
 * AUTOMATIC CONVERTER & CALCULATOR CLASSIFICATION ENGINE
 * 
 * Enforces Chapter 25 architecture rules for UnitsConvertors.com:
 * 1. Unit Converters:
 *    - Fixed mathematical conversion ratio
 *    - 1 input, 1 output
 *    - No assumptions, no external variables
 *    - SI / NIST / ISO standardized exact mathematical relationship
 * 
 * 2. Engineering Calculators:
 *    - Requires external variables (distance, area, beam angle, temperature, pressure, humidity, material properties, etc.)
 *    - Multi-variable physical models & engineering equations
 *    - Explicit governing equations and mandatory physical assumptions
 */

export type PageClassificationType = "unit-converter" | "engineering-calculator";

export interface ClassificationResult {
  type: PageClassificationType;
  category: string;
  isExactMath: boolean;
  requiresExternalVariables: boolean;
  hasAssumptions: boolean;
  indexingPolicy: "index, follow" | "noindex, follow";
  reason: string;
}

export interface ContentQualityMetrics {
  hasOriginalArticle?: boolean;
  hasFormula?: boolean;
  hasWorkedExamples?: boolean;
  hasReferenceTable?: boolean;
  hasFaqs?: boolean;
  faqCount?: number;
  hasPracticalApplications?: boolean;
  wordCount?: number;
}

// 32 Unit Converter Categories (Exact SI / NIST / ISO standard physical quantities)
export const UNIT_CONVERTER_CATEGORIES = [
  "length",
  "weight-mass",
  "area",
  "volume",
  "temperature",
  "time",
  "speed",
  "pressure",
  "energy",
  "power",
  "fuel-economy",
  "cooking",
  "data-storage",
  "engineering", // Density
  "electrical", // Voltage
  "scientific", // Amount of Substance
  "light", // Illumination
  "sound",
  "force",
  "flow",
  "angle",
  "electricity", // Electric Current
  "construction",
  "data-transfer",
  "solid-angle",
  "torque",
  "acceleration",
  "electric-resistance",
  "capacitance",
  "inductance",
  "electric-charge",
  "radioactivity"
] as const;

// 11 Engineering Calculator Disciplines (Multi-variable physical models)
export const ENGINEERING_CALCULATOR_DISCIPLINES = [
  "electrical-calc",
  "mechanical-calc",
  "civil-calc",
  "physics-calc",
  "optics-light-calc",
  "thermodynamics-calc",
  "chemistry-calc",
  "fluid-mechanics-calc",
  "electronics-calc",
  "mathematics-calc",
  "general-engineering-calc"
] as const;

/**
 * Step 1 & 3: Automatic Classifier
 * Inspects inputs, variables, assumptions, and category to classify as Unit Converter or Engineering Calculator.
 */
export function classifyToolOrPage(params: {
  categoryId?: string;
  inputsCount?: number;
  externalVariables?: string[];
  assumptions?: string[];
  formula?: string;
}): ClassificationResult {
  const { categoryId, inputsCount = 1, externalVariables = [], assumptions = [] } = params;

  const hasExternalVars = externalVariables.length > 0;
  const hasAssump = assumptions.length > 0;
  const isMultiInput = inputsCount > 1;

  // Check category registry if matching known discipline
  const isKnownCalcDiscipline = categoryId && ENGINEERING_CALCULATOR_DISCIPLINES.includes(categoryId as any);
  const isKnownConverterCategory = categoryId && UNIT_CONVERTER_CATEGORIES.includes(categoryId as any);

  if (isKnownCalcDiscipline || isMultiInput || hasExternalVars || hasAssump) {
    return {
      type: "engineering-calculator",
      category: categoryId || "general-engineering-calc",
      isExactMath: false,
      requiresExternalVariables: true,
      hasAssumptions: hasAssump,
      indexingPolicy: "index, follow", // default hub or evaluated
      reason: "Requires multi-variable inputs, external physical parameters, or explicit engineering assumptions."
    };
  }

  return {
    type: "unit-converter",
    category: categoryId || "length",
    isExactMath: true,
    requiresExternalVariables: false,
    hasAssumptions: false,
    indexingPolicy: "index, follow",
    reason: "Exact 1:1 mathematical unit conversion without external assumptions or secondary variables."
  };
}

/**
 * Step 5: SEO Indexing Policy Evaluator
 * Category Hub pages -> always 'index, follow'
 * Individual Converter / Calculator pages:
 *   - 'index, follow' if comprehensive educational content (article, formula, examples, tables, FAQs)
 *   - 'noindex, follow' if thin form or autogenerated content
 */
export function evaluateSeoPolicy(
  pageType: "home" | "category-hub" | "individual-tool" | "support-page",
  contentQuality?: ContentQualityMetrics
): "index, follow" | "noindex, follow" {
  // Support pages and Category Hub pages are authoritative indexable pages
  if (pageType === "home" || pageType === "category-hub" || pageType === "support-page") {
    return "index, follow";
  }

  if (!contentQuality) {
    // Default fallback for individual tool pages without evaluated content metrics
    return "index, follow";
  }

  // Evaluate content depth criteria
  const meetsWordCount = (contentQuality.wordCount || 0) >= 300;
  const hasFaqs = (contentQuality.faqCount || 0) >= 3 || contentQuality.hasFaqs;
  const hasEducationalSections = 
    Boolean(contentQuality.hasOriginalArticle) &&
    Boolean(contentQuality.hasFormula) &&
    Boolean(contentQuality.hasWorkedExamples) &&
    Boolean(contentQuality.hasReferenceTable);

  if (hasEducationalSections && hasFaqs && meetsWordCount) {
    return "index, follow";
  }

  // Thin content pages receive noindex, follow to protect site quality
  return "noindex, follow";
}

/**
 * Step 5 & 6: Automated Meta Tag & Indexing Applier
 * Sets dynamic title, description, canonical link, and robots index/noindex header tag.
 */
export function applyAutomatedSeo(params: {
  pageType: "home" | "category-hub" | "individual-tool" | "support-page";
  title: string;
  description: string;
  canonicalUrl?: string;
  contentQuality?: ContentQualityMetrics;
}) {
  const robotsPolicy = evaluateSeoPolicy(params.pageType, params.contentQuality);
  
  // Apply title, description, canonical
  updatePageMeta(params.title, params.description, params.canonicalUrl);

  // Apply robots meta tag
  updateRobotsTag(robotsPolicy === "index, follow");

  return robotsPolicy;
}

/**
 * Step 6: Future-Proof Registration Workflow
 * Registers a new converter or calculator page, classifies it automatically,
 * determines its correct category, applies SEO policy, and returns registration metadata.
 */
export function registerToolPage(toolDefinition: {
  id: string;
  name: string;
  category: string;
  inputsCount?: number;
  externalVariables?: string[];
  assumptions?: string[];
  contentQuality?: ContentQualityMetrics;
}) {
  const classification = classifyToolOrPage({
    categoryId: toolDefinition.category,
    inputsCount: toolDefinition.inputsCount,
    externalVariables: toolDefinition.externalVariables,
    assumptions: toolDefinition.assumptions
  });

  const seoPolicy = evaluateSeoPolicy("individual-tool", toolDefinition.contentQuality);

  return {
    id: toolDefinition.id,
    name: toolDefinition.name,
    classification,
    seoPolicy,
    registeredAt: new Date().toISOString()
  };
}
